"""Compatibility for existing scripts importing helpers from app.

New code should import the owning feature module directly.
"""

from importlib import import_module

EXPORT_GROUPS = {
    'amazon_catalog': (
        '_amazon_build_price_feed_xml', '_amazon_download_feed_document', '_amazon_find_local_sku_by_asin',
        '_amazon_get_catalog_product_type', '_amazon_get_feed_document_info', '_amazon_get_feed_status',
        '_amazon_get_listing_product_type', '_amazon_marketplace_from_id', '_amazon_parse_feed_report',
        '_amazon_resolve_asin_from_upc', '_amazon_spapi_context', '_amazon_submit_price_feed',
        '_amazon_submit_price_feed_json', '_amazon_submit_price_feed_xml',
        'api_listingagent_amazon_account_check', 'api_listingagent_amazon_catalog_item',
        'api_listingagent_amazon_catalog_search', 'api_listingagent_amazon_get_listing',
        'api_listingagent_amazon_restriction_check',
    ),
    'amazon_listing': (
        '_LISTINGAGENT_AMAZON_RESTRICTIONS_CACHE', '_LISTINGAGENT_AMAZON_RESTRICTIONS_LOCK',
        '_LISTINGAGENT_AMAZON_RESTRICTIONS_TTL', '_amazon_check_listing_restrictions',
        '_amazon_check_listing_restrictions_cached', '_amazon_create_feed', '_amazon_create_feed_document',
        '_amazon_feeds_error', '_amazon_format_spapi_error', '_amazon_manual_listing_bullets',
        '_amazon_manual_listing_text', '_amazon_normalize_condition_type',
        '_amazon_normalize_fulfillment_channel', '_amazon_offer_audience', '_amazon_offer_price_attrs',
        '_amazon_price_value_key', '_amazon_restriction_error_hints', '_amazon_update_price_spapi',
        '_build_amazon_manual_listing_attributes', '_build_amazon_offer_attributes',
    ),
    'amazon_orders': (
        'get_amazon_orders', 'repair_amazon_listing_titles', 'sync_amazon_listings', 'sync_amazon_orders',
        'test_amazon_connection',
    ),
    'amazon_publish': (
        'api_listingagent_amazon_put_offer',
    ),
    'analytics': (
        'api_amazon_financial_summary', 'api_financial_analytics', 'api_inventory_age_rescan',
        'api_inventory_age_summary', 'api_inventory_cleanup', 'api_inventory_quantity_history',
        'api_inventory_seller_analytics', 'api_refresh_sold_data', 'api_sold_performance_history',
    ),
    'background': (
        '_background_tasks_lock_handle', 'delayed_start', 'start_background_services',
    ),
    'bol_inventory': (
        'api_bol_items', 'api_bol_items_set_list_status', 'api_bol_lots', 'api_bulk_delete_bol_items',
        'api_set_selected_lot', 'get_bol_upcs',
    ),
    'bulk_manifest': (
        '_bulk_manifest_candidate_barcodes', '_bulk_manifest_delete_manifest',
        '_bulk_manifest_delete_photo_files', '_bulk_manifest_google_image_formula',
        '_bulk_manifest_google_link_formula', '_bulk_manifest_is_macy_image_host',
        '_bulk_manifest_load_detail', '_bulk_manifest_load_photos', '_bulk_manifest_lookup_rawbol',
        '_bulk_manifest_lot_average_price', '_bulk_manifest_macy_full_image_url',
        '_bulk_manifest_macy_thumb_url', '_bulk_manifest_money', '_bulk_manifest_next_title',
        '_bulk_manifest_normalize_image_url', '_bulk_manifest_parse_ids', '_bulk_manifest_photo_abs_path',
        '_bulk_manifest_photo_counts', '_bulk_manifest_photo_label_text', '_bulk_manifest_photo_payload',
        '_bulk_manifest_photo_url', '_bulk_manifest_pick_price_column', '_bulk_manifest_prepare_items',
        '_bulk_manifest_price_numeric_expr', '_bulk_manifest_random_unit_price',
        '_bulk_manifest_rawbol_price_column', '_bulk_manifest_replace_items',
        '_bulk_manifest_resolve_unit_price', '_bulk_manifest_save_labeled_photo',
        '_bulk_manifest_status_key', '_ensure_bulk_manifest_tables', '_listagent_is_macy_image_url',
        '_listagent_prioritize_macy_thumbnail', '_marketplace_sale_store_key',
        'api_bulk_manifest_add_photos', 'api_bulk_manifest_cleanup_items', 'api_bulk_manifest_create',
        'api_bulk_manifest_delete', 'api_bulk_manifest_detail', 'api_bulk_manifest_google_sheet',
        'api_bulk_manifest_google_sheet_delete', 'api_bulk_manifest_google_sheet_health',
        'api_bulk_manifest_google_sheet_status', 'api_bulk_manifest_history', 'api_bulk_manifest_lookup',
        'api_bulk_manifest_mark_sold', 'api_bulk_manifest_photos', 'api_bulk_manifest_refresh',
        'api_bulk_manifest_search', 'api_bulk_manifest_update', 'bulk_manifest_page',
        'bulk_manifest_pictures_page',
    ),
    'cache_admin': (
        'CACHE_CONFIG_FILE', 'api_admin_clear_cache', 'api_cache_settings', 'api_enrich_sold_db',
        'cache_scheduler_loop', 'load_cache_config', 'save_cache_config',
    ),
    'caching': (
        '_invalidate_searchrack_cache', '_listing_helper_scan_cache_clear',
        '_listing_helper_scan_cache_get', '_listing_helper_scan_cache_set', 'api_clear_cache',
        'api_data_version', 'get_data_version', 'update_data_version',
    ),
    'config': (
        'BASE_DIR', 'CLIENT_ID', 'CLIENT_SECRET', 'DEBUG_MODE', 'RUNAME', 'logger',
    ),
    'database': (
        '_bol_items_fast_indexes_ready', '_ensure_bol_items_fast_indexes', '_sqlite_ident',
        'close_db_connections', 'create_database_indexes', 'db_connection', 'enable_wal_mode',
        'get_db_connection',
    ),
    'diagnostics': (
        'api_cleanup_temporary_entry', 'api_create_test_sold_order', 'api_debug_check_item',
        'api_debug_migrate_listings', 'test_sold_orders_page',
    ),
    'ebay_auth': (
        'access_token', 'api_token_status', 'callback', 'headers', 'home', 'token_status',
    ),
    'ebay_catalog': (
        '_LISTINGAGENT_EBAY_APP_TOKEN', '_LISTINGAGENT_EBAY_APP_TOKEN_LOCK',
        '_LISTINGAGENT_EBAY_ASPECTS_CACHE', '_LISTINGAGENT_EBAY_ASPECTS_LOCK',
        '_LISTINGAGENT_EBAY_CATEGORY_TREE_ID', '_LISTINGAGENT_EBAY_CATEGORY_TREE_LOCK',
        '_ebay_buy_api_request', '_ebay_catalog_aspects_to_dict',
        '_listingagent_browse_items_to_candidates', '_listingagent_detect_color_tokens',
        '_listingagent_ebay_browse_aspects_to_dict', '_listingagent_ebay_browse_category_fields',
        '_listingagent_ebay_candidate_key', '_listingagent_ebay_title_tokens',
        '_listingagent_ebay_user_request', '_listingagent_get_ebay_app_token',
        '_listingagent_get_ebay_browse_item_detail', '_listingagent_get_ebay_category_aspects',
        '_listingagent_get_ebay_category_tree_id', '_listingagent_merge_ebay_candidates',
        '_listingagent_normalize_ebay_catalog_summary', '_listingagent_pick_best_ebay_candidate',
        '_listingagent_score_ebay_candidate', '_listingagent_search_ebay_browse_candidates',
        'api_listingagent_ebay_catalog_item', 'api_listingagent_ebay_catalog_search',
        'api_listingagent_ebay_category_aspects', 'api_listingagent_ebay_category_suggestions',
        'api_listingagent_ebay_comps', 'api_listingagent_ebay_product_specifics',
    ),
    'ebay_orders': (
        '_EBAY_CONDITION_ID_LABELS', '_ebay_item_text_details', 'get_ebay_orders', 'orders',
    ),
    'ebay_policies': (
        '_LISTINGAGENT_EBAY_CONDITIONS_CACHE', '_LISTINGAGENT_EBAY_CONDITIONS_LOCK',
        '_LISTINGAGENT_EBAY_LOCATIONS_CACHE', '_LISTINGAGENT_EBAY_LOCATIONS_LOCK',
        '_LISTINGAGENT_EBAY_POLICIES_CACHE', '_LISTINGAGENT_EBAY_POLICIES_LOCK',
        '_build_ebay_inventory_item_payload', '_build_ebay_offer_payload', '_ebay_api_request',
        '_ebay_extract_error', '_extract_missing_ebay_aspect', '_listingagent_condition_enum_from_policy',
        '_listingagent_dedupe_image_urls', '_listingagent_find_existing_offer_for_sku',
        '_listingagent_get_condition_candidates', '_listingagent_get_ebay_allowed_condition_enums',
        '_listingagent_get_ebay_business_policies', '_listingagent_get_ebay_location_keys',
        '_listingagent_get_ebay_locations', '_listingagent_has_mixed_ebay_image_sources',
        '_listingagent_is_amazon_image_url', '_listingagent_is_ebay_eps_url',
        '_listingagent_is_likely_ebay_image_mix_error', '_listingagent_prefer_single_ebay_image_source',
        '_listingagent_put_inventory_item_with_condition_fallback',
        '_listingagent_resolve_ebay_location_key', 'api_listingagent_ebay_business_policies',
        'api_listingagent_ebay_locations', 'api_listingagent_ebay_offers_for_sku',
    ),
    'ebay_publish': (
        '_EBAY_STORE_POLICIES_HTML', '_listingagent_ebay_create_draft_offer',
        '_publish_mapped_ebay_listing', 'api_listingagent_ebay_draft',
        'api_listingagent_ebay_generate_description', 'api_listingagent_ebay_generate_title',
        'api_listingagent_ebay_publish',
    ),
    'email_settings': (
        'emailer', 'get_emailer_settings', 'save_emailer_settings', 'send_email_smtp', 'send_health_email',
        'send_test_email', 'send_test_inventory_email',
    ),
    'enrichment': (
        '_enrich_lock', '_enrich_status', '_run_enrich_in_background', 'api_enrich_status',
        'api_refresh_searchrack', 'maybe_run_startup_enrich',
    ),
    'errors': (
        '_ListingAgentUserError', '_safe_error', 'handle_file_too_large', 'require_debug_mode',
    ),
    'facebook': (
        '_ensure_fbstore_log_tables', '_ensure_fbstore_notes_tables', '_ensure_fbstore_tables',
        '_log_fb_listing_action', '_track_fb_listing', 'api_fb_listings', 'api_fb_listings_add',
        'api_fb_listings_log', 'api_fb_listings_log_undo', 'api_fb_listings_notes_add',
        'api_fb_listings_notes_delete', 'api_fb_listings_notes_get', 'api_fb_listings_notes_update',
        'api_fb_listings_quantity', 'api_fb_listings_search_rawbol', 'api_fb_listings_sync_sold',
        'api_fb_listings_unlist',
    ),
    'fba_inventory': (
        '_FBA_GENERIC_BIN_RE', '_FBA_NAMED_BIN_RE', '_fba_apply_inventory_offer_strategy',
        '_fba_batch_payload', '_fba_bin_parent_code', '_fba_inventory_state_for_barcode',
        '_fba_local_amazon_listing', '_fba_local_amazon_listing_by_asin',
        '_fba_marketplace_status_for_barcodes', '_fba_plan_item_signature', '_fba_proposed_seller_sku',
        '_fba_review_reasons', '_fba_session_item_payload', '_fba_session_row_payload',
        '_fba_working_locations_payload',
    ),
    'fba_readiness': (
        '_FBA_AMAZON_BARCODE_GUIDANCE_CACHE', '_FBA_AMAZON_BARCODE_GUIDANCE_LOCK',
        '_FBA_AMAZON_BARCODE_GUIDANCE_TTL', '_FBA_ITEM_LABEL_PRINT_LOCK', '_FBA_LISTING_READINESS_CACHE',
        '_FBA_LISTING_READINESS_CACHE_LOCK', '_FBA_LISTING_READINESS_CACHE_TTL',
        '_FBA_REQUIRED_SAFETY_FIELDS', '_fba_amazon_barcode_guidance',
        '_fba_amazon_barcode_guidance_for_listings', '_fba_amazon_barcode_guidance_result',
        '_fba_amazon_barcode_guidance_unavailable', '_fba_apply_listing_readiness',
        '_fba_catalog_measurement_reference', '_fba_catalog_measurement_reference_from_payload',
        '_fba_create_separate_fba_offer', '_fba_enablement_progress', '_fba_error_is_missing_safety_info',
        '_fba_existing_prep_conflict', '_fba_inbound_activation_message', '_fba_inbound_unavailable_skus',
        '_fba_issue_is_missing_safety_info', '_fba_item_prep_details', '_fba_listing_issue_message',
        '_fba_listing_readiness', '_fba_listings_client', '_fba_missing_prep_mskus',
        '_fba_normalize_prep_detail', '_fba_package_measurement_issues',
        '_fba_patch_listing_no_battery_safety', '_fba_patch_listing_package_measurements',
        '_fba_patch_listing_to_fba', '_fba_positive_measurement', '_fba_update_enablement_results',
        'api_fba_prep_barcode_guidance', 'api_fba_prep_enable_fba', 'api_fba_prep_enable_fba_status',
        'api_fba_prep_resolve_amazon_skus', 'api_fba_prep_resolve_fba_safety',
        'api_fba_prep_validate_inbound',
    ),
    'fba_scanning': (
        '_fba_planned_label_match', 'api_fba_labels_resolve', 'api_fba_prep_amazon_move_box_scan',
        'api_fba_prep_amazon_pack_scan', 'api_fba_prep_amazon_print_item_label',
        'api_fba_prep_amazon_reset_pack_scan', 'api_fba_prep_count_scan',
    ),
    'fba_schema': (
        '_ensure_fba_prep_tables', '_fba_client_identity', '_fba_json_dict', '_fba_json_list',
        '_fba_touch_session_worker', '_fba_trim',
    ),
    'fba_sessions': (
        '_fba_review_rows', 'api_fba_prep_batch_detail', 'api_fba_prep_batches', 'api_fba_prep_items',
        'api_fba_prep_review_update', 'api_fba_prep_reviews', 'api_fba_prep_session_detail',
        'api_fba_prep_session_live', 'api_fba_prep_sessions',
    ),
    'fba_shipments': (
        '_fba_amazon_box_label_document', '_fba_amazon_client', '_fba_amazon_collect',
        '_fba_amazon_exception_detail', '_fba_amazon_option_summary', '_fba_amazon_payload',
        '_fba_amazon_refresh_operation', '_fba_amazon_session', '_fba_amazon_source_from_settings',
        '_fba_amazon_state', '_fba_amazon_sync_recovery', '_fba_amazon_sync_snapshot',
        '_fba_amazon_transport_summary', '_fba_choose_compatible_recovery_packing',
        '_fba_packed_quantities', '_fba_prepare_and_create_plan', '_fba_recovery_fnsku_mismatches',
        '_fba_recovery_option_groups', '_fba_recovery_save_updated_items', '_fba_save_amazon_state',
        '_fba_set_amazon_operation', '_fba_transport_option_can_purchase', 'api_fba_prep_amazon_action',
        'api_fba_prep_amazon_box_labels', 'api_fba_prep_amazon_plans', 'api_fba_prep_amazon_readiness',
        'api_fba_prep_amazon_sync',
    ),
    'finder': (
        '_finder_barcode_search_variants', 'api_finder', 'api_finder_assign', 'api_finder_forget_alias',
        'api_finder_records', 'api_finder_remove', 'api_finder_undo_remove', 'api_lookup_image_by_barcode',
        'finder_page',
    ),
    'health': (
        'collect_health_stats', 'format_time_ago', 'generate_health_email_html',
        'generate_health_email_plain',
    ),
    'integrations': (
        'AMAZON_AVAILABLE', 'AmazonManager', 'BOL_AVAILABLE', 'process_bol_excel',
        'process_bol_retail_backfill',
    ),
    'inventory_age': (
        '_backfill_inventory_age_batches', '_ensure_inventory_age_schema', '_inventory_age_consume_fifo',
        '_inventory_age_insert_batch', '_inventory_age_received_at', '_inventory_age_transfer_fifo',
        '_reconcile_inventory_age_batches',
    ),
    'inventory_age_evidence': (
        '_inventory_age_base_key', '_inventory_age_confidence_label',
        '_inventory_age_depleted_raw_capacity', '_inventory_age_evidence_paths', '_inventory_age_exact_key',
        '_inventory_age_group_plan', '_inventory_age_ledger_signature', '_inventory_age_load_history',
        '_inventory_age_load_receipt_evidence', '_inventory_age_lot_key', '_inventory_age_read_ledger_rows',
        '_inventory_age_replay_history', '_inventory_age_unit_signature',
    ),
    'inventory_age_rescan': (
        '_inventory_age_rescan_lock', '_rescan_inventory_age_from_history',
    ),
    'inventory_alerts': (
        '_start_emailer_alert_thread', 'collect_inventory_mismatches', 'emailer_alert_worker',
        'generate_inventory_email_html', 'generate_inventory_email_plain', 'send_inventory_alert_email',
    ),
    'inventory_archives': (
        'api_archived_list', 'api_debug_db_check', 'api_delete_archive', 'api_delete_row',
        'api_location_duplicates', 'api_trash_hard_delete', 'api_trash_hard_delete_all', 'api_trash_list',
        'api_trash_purge_expired', 'api_trash_restore', 'api_trash_settings', 'api_undelete',
        'trash_manager_page',
    ),
    'inventory_cleanup': (
        '_automatic_removal_started', '_process_automatic_inventory_removals', '_purge_expired_trash',
        '_purge_zero_qty_items', '_start_automatic_removal_thread', '_start_trash_purger_thread',
        '_start_zero_qty_deleter_thread', '_trash_purger_started', '_zero_qty_deleter_started',
        'api_get_grace_period', 'api_get_zero_qty_pending', 'api_get_zero_qty_settings',
        'api_set_grace_period', 'api_set_zero_qty_settings', 'api_trigger_zero_qty_purge',
        'api_zero_qty_allow', 'api_zero_qty_cancel', 'api_zero_qty_delete_now', 'cleanup_page',
    ),
    'inventory_history': (
        '_capture_legacy_zero_searchrack_rows', '_clear_zero_qty_pending_deletions',
        '_ensure_legacy_removed_table', '_ensure_removed_items_table', '_ensure_searchrack_history_outbox',
        '_ensure_searchrack_snapshot_columns', '_ensure_searchrack_undo_claims',
        '_flush_searchrack_history_outbox', '_history_event_candidate', '_history_restore_quantity',
        '_history_timestamp', '_initialize_searchrack_history_guard', '_insert_inventory_undo_history',
        '_install_searchrack_history_guard', '_inventory_age_lookup',
        '_mark_zero_qty_for_deletion_external', '_record_inventory_zero_transition',
        '_restore_searchrack_from_history', '_restore_searchrack_with_undo_claim', '_row_casefold_dict',
        '_searchrack_history_flush_lock', '_searchrack_snapshot_location', '_searchrack_snapshot_value',
        '_searchrack_trigger_integral_quantity', '_searchrack_trigger_location',
        '_searchrack_trigger_snapshot', '_searchrack_trigger_value',
    ),
    'inventory_history_views': (
        '_find_legacy_removed_detail', 'api_inventory_history', 'api_removed_list', 'api_removed_undo',
        'api_sold_remove_now', 'removed_page', 'undo_match',
    ),
    'listing_alerts': (
        '_ensure_listing_alerts_tables', '_listing_alert_base_upc_key', '_listing_alert_upc_key',
        '_listing_helper_scan_cache_lock', '_listing_helper_scan_cache_state',
        '_listing_inventory_match_for_order', '_load_listing_inventory_match_lookup',
        '_normalize_store_listing_identity', '_store_listing_order_identity_candidates',
        'api_listing_helper_dismiss', 'api_listing_helper_dismissed', 'api_listing_helper_inventory_match',
        'api_listing_helper_scan', 'api_listing_helper_undismiss',
    ),
    'listing_checks': (
        '_listagent_add_check_media', '_listagent_add_check_note', '_listagent_check_request_defaults',
        '_listagent_enrich_check_request_rows', '_listagent_get_check_media', '_listagent_get_check_notes',
        '_listagent_get_check_request', '_listagent_get_check_request_statuses',
        '_listagent_get_check_requests', '_listagent_init_tables', '_listagent_mark_check_request_complete',
        '_listagent_now_iso', '_listagent_row_to_dict', '_listagent_set_check_request',
    ),
    'listing_lifecycle': (
        '_apply_marketplace_status_overlay', '_chunk_list', '_ensure_bol_list_status_column',
        '_fetch_auto_marketplace_listing_links', '_fetch_live_marketplace_upc_keys',
        '_is_marketplace_live_for_upc', '_legacy_migrate_list_status_to_amazon',
        '_listing_center_mark_bol_listed', '_listing_source_label', '_marketplace_upc_lookup_variants',
        'ensure_lifecycle_tables',
    ),
    'listing_log': (
        '_listinglog_add_entry', '_listinglog_init_tables', 'api_listinglog_recent', 'page_listing_log',
    ),
    'listing_queue': (
        '_items_to_list_upc_search_variants', '_listagent_add_photo', '_listagent_add_to_queue',
        '_listagent_delete_working_draft', '_listagent_format_upc12', '_listagent_get_photos',
        '_listagent_get_queue', '_listagent_get_queue_statuses', '_listagent_get_working_draft',
        '_listagent_get_working_draft_statuses', '_listagent_localize_image_urls', '_listagent_mark_listed',
        '_listagent_photo_path_exists', '_listagent_remove_from_queue', '_listagent_search_live_listings',
        '_listagent_upc_variants', '_listagent_upsert_working_draft',
        'api_listingagent_live_listings_search', 'api_listingagent_photos_get',
        'api_listingagent_photos_upload', 'api_listingagent_upc_detail', 'api_listingagent_upc_search',
    ),
    'listing_settings': (
        '_listagent_normalize_added_mode', '_listingagent_get_settings',
        '_listingagent_init_settings_table', '_listingagent_parse_float', '_listingagent_parse_int',
        '_listingagent_upsert_settings', 'api_listingagent_check_media_get',
        'api_listingagent_check_media_upload', 'api_listingagent_check_notes_add',
        'api_listingagent_check_notes_get', 'api_listingagent_check_request_complete',
        'api_listingagent_check_request_get', 'api_listingagent_check_request_save',
        'api_listingagent_check_requests', 'api_listingagent_delete_working_draft',
        'api_listingagent_get_settings', 'api_listingagent_get_working_draft', 'api_listingagent_queue',
        'api_listingagent_queue_add', 'api_listingagent_queue_mark_listed', 'api_listingagent_queue_remove',
        'api_listingagent_queue_statuses', 'api_listingagent_save_settings',
        'api_listingagent_save_working_draft', 'check_items', 'items_to_list_mobile_photos', 'listingagent',
        'listingagent_mobile',
    ),
    'mail_center': (
        '_MAIL_AMAZON_BUYER_HINTS', '_MAIL_AMAZON_HINTS', '_MAIL_AMAZON_ORDER_ID_RE',
        '_mail_center_env_int', '_mail_center_hourly_refresh_once', '_mail_clean_message_id',
        '_mail_date_to_iso', '_mail_decode_header_value', '_mail_ebay_get_member_messages',
        '_mail_ebay_headers', '_mail_ebay_send_reply', '_mail_extract_text_body', '_mail_html_to_text',
        '_mail_message_to_dict', '_mail_parse_forwarded_amazon_email', '_mail_parse_payload',
        '_mail_store_upsert_external', '_mail_strip_subject_prefixes', '_mail_sync_amazon',
        '_mail_sync_amazon_forwarded_emails', '_mail_sync_ebay', '_start_mail_center_refresh_thread',
        '_verify_sns_signature', 'api_amazon_sns_webhook', 'api_mail_center_create_message',
        'api_mail_center_mark_read', 'api_mail_center_messages', 'api_mail_center_reply',
        'api_mail_center_send', 'api_mail_center_sync', 'mail_center_refresh_worker',
    ),
    'mail_schema': (
        '_ensure_storemail_tables', '_normalize_mail_store',
    ),
    'manifest_google': (
        '_bulk_manifest_build_google_sheet_rows', '_bulk_manifest_google_access_token',
        '_bulk_manifest_google_delete_manifest', '_bulk_manifest_google_delete_sheet_resource',
        '_bulk_manifest_google_ensure_manifest_sheet', '_bulk_manifest_google_export_manifest',
        '_bulk_manifest_google_export_sheet', '_bulk_manifest_google_export_worker',
        '_bulk_manifest_google_get_spreadsheet', '_bulk_manifest_google_health',
        '_bulk_manifest_google_job_clear', '_bulk_manifest_google_job_get', '_bulk_manifest_google_job_set',
        '_bulk_manifest_google_jobs', '_bulk_manifest_google_jobs_lock',
        '_bulk_manifest_google_manifest_meta', '_bulk_manifest_google_request',
        '_bulk_manifest_google_request_error', '_bulk_manifest_google_share_email',
        '_bulk_manifest_google_share_sheet', '_bulk_manifest_google_shared_spreadsheet_id',
        '_bulk_manifest_google_sheet_range', '_bulk_manifest_google_should_recreate_sheet',
        '_bulk_manifest_google_state', '_bulk_manifest_google_status_payload',
        '_bulk_manifest_google_style_sheet', '_bulk_manifest_google_tab_title',
        '_bulk_manifest_google_timeout', '_bulk_manifest_google_write_sheet_rows',
        '_bulk_manifest_queue_google_export',
    ),
    'marketplace_removal': (
        '_apply_marketplace_removal_plan', '_build_marketplace_removal_plan',
        '_marketplace_lookup_rawbol_item', '_normalize_marketplace_allocations', '_probe_ebay_listing_live',
    ),
    'marketplace_sales': (
        'api_marketplace_decrement', 'api_marketplace_lookup', 'api_marketplace_pickups',
        'api_marketplace_pickups_create', 'api_marketplace_pickups_search', 'api_marketplace_sale',
        'api_marketplace_sale_delete', 'api_marketplace_sale_update', 'api_marketplace_sales',
        'api_marketplace_search', 'marketplace_generate_barcode', 'marketplace_live_pickups',
        'marketplace_sale', 'marketplace_schedule_pickup', 'marketplace_session', 'marketplace_stats',
    ),
    'normalization': (
        '_coerce_bool', '_coerce_int', '_format_upc_display', '_is_items_to_list_suffixed_upc',
        '_items_to_list_asset_scope', '_items_to_list_bucket_status', '_items_to_list_effective_status',
        '_normalize_listing_source', '_normalize_lot_number', '_normalize_prep_row_status',
        '_normalize_scanned_upc', '_normalize_upc', '_normalize_upc_preserve_suffix_for_match', '_now_iso',
        '_parse_iso_utc_naive', '_sold_order_sale_datetime', '_sold_removal_event_is_current',
        '_strict_inventory_quantity', '_strip_leading_zeros_numeric',
    ),
    'pages': (
        'alerts_page', 'barcode_print_que', 'barcode_print_view', 'bol_stats_page', 'extractor',
        'fb_listings_page', 'financial_analytics', 'inventory_cleanup_decisions',
        'inventory_seller_analytics', 'items_to_list_page', 'label_master_page', 'mail_center_page', 'misc',
        'prep_media_cleaner_page', 'price_master_page', 'privacy', 'ready_to_ship_page',
        'ready_to_ship_prep_context', 'ready_to_ship_prep_summaries', 'refresh_searchrack', 'search',
        'shelfcreator', 'shelfmanager', 'store_listing_helper_page', 'store_manager_page', 'sync',
        'test_sold_item', 'tools',
    ),
    'payouts': (
        'api_get_payouts', 'api_sync_payouts', 'payouts_page',
    ),
    'prep_actions': (
        'api_bol_items_update_quantity', 'api_items_prep_allocate_lots', 'api_items_prep_cleanup_temp',
        'api_items_prep_create_bad_entry', 'api_items_prep_create_return_entry',
        'api_items_prep_good_entries', 'api_items_prep_status', 'api_items_prep_status_delete',
        'api_items_prep_status_get',
    ),
    'prep_context': (
        '_build_ready_to_ship_prep_context', '_build_suffixed_item_prep_context',
        '_empty_suffixed_item_prep_summary', '_items_prep_scope_has_actionable_status',
        '_load_suffixed_item_prep_summary_lookup', '_ready_to_ship_prep_related_like',
        '_ready_to_ship_prep_relevance', '_ready_to_ship_prep_relevance_label',
        '_ready_to_ship_prep_sort_value', '_suffixed_item_prep_variants', 'api_bol_lookup',
        'api_items_prep_auto_assign_lot', 'api_warehouse_item_prep_context',
    ),
    'prep_diagnostics': (
        'api_items_prep_delete_photo', 'api_items_prep_diagnostic', 'api_items_prep_diagnostic_add_photos',
        'api_items_prep_diagnostic_delete_photos', 'api_items_prep_diagnostic_get',
        'api_items_prep_diagnostic_history', 'api_items_prep_diagnostic_live_listings',
        'api_items_prep_diagnostic_reset', 'api_items_prep_set_display_image', 'api_items_prep_trash_list',
        'api_items_prep_trash_restore',
    ),
    'prep_locations': (
        'api_items_prep_location_clear', 'api_items_prep_location_get', 'api_items_prep_location_set',
        'api_items_prep_reset',
    ),
    'prep_log': (
        '_listinglog_meta_dict', '_preplog_add_entry', '_preplog_apply_quantity_change',
        '_preplog_attach_titles', '_preplog_attach_voice_notes', '_preplog_auto_assigned_entries',
        '_preplog_enrich_row', '_preplog_init_tables', '_preplog_mark_undone', '_preplog_meta_dict',
        '_preplog_recent', '_preplog_set_undo_error', '_preplog_sync_downstream_delete',
        '_preplog_update_meta', 'api_preplog_reassign_lot', 'api_preplog_recent', 'api_preplog_undo',
        'api_preplog_update',
    ),
    'prep_media': (
        '_ensure_app_settings', '_items_prep_delete_diagnostic_assets', '_items_prep_delete_image_rows',
        '_items_prep_delete_media_rows', '_items_prep_delete_note_rows', '_move_to_trash',
        '_prep_media_cleaner_abs_path', '_prep_media_cleaner_allowed_types',
        '_prep_media_cleaner_delete_rows', '_prep_media_cleaner_filter_rows',
        '_prep_media_cleaner_format_bytes', '_prep_media_cleaner_load_rows',
        '_prep_media_cleaner_normalize_upc_filter', '_prep_media_cleaner_row_lots',
        '_prep_media_cleaner_summary', '_set_trash_retention_days', '_trash_retention_days',
        'api_items_prep_diagnostic_photos_zip', 'api_items_prep_media_add', 'api_items_prep_media_delete',
        'api_items_prep_media_get', 'api_items_prep_notes_add', 'api_items_prep_notes_delete',
        'api_items_prep_notes_get', 'api_prep_media_cleaner_delete', 'api_prep_media_cleaner_overview',
        'api_prep_media_cleaner_query',
    ),
    'prep_schema': (
        '_ITEMS_PREP_ENSURE_MIN_INTERVAL_SECONDS', '_ensure_items_prep_tables', '_items_prep_ensure_lock',
        '_items_prep_ensure_state', '_items_prep_record_exception',
    ),
    'prep_undo': (
        '_items_prep_delete_orphan_history_status', '_items_prep_undo_core',
        'api_items_prep_history_entry_delete', 'api_items_prep_undo',
    ),
    'prep_views': (
        'item_prep_diagnostic_page', 'item_prep_diagnostic_view_page', 'item_prep_log_page',
        'item_prep_no_barcode_page', 'item_prep_page', 'search_rawbol_api',
    ),
    'pricing': (
        '_pricemaster_compute_new_price', '_pricemaster_ebay_get_item_price',
        '_pricemaster_ebay_revise_prices_bulk', '_pricemaster_ebay_trading_call',
        '_pricemaster_fetch_amazon_rows', '_pricemaster_fetch_ebay_rows', '_pricemaster_get_feed_job',
        '_pricemaster_get_meta_map', '_pricemaster_init_tables', '_pricemaster_money_2dp',
        '_pricemaster_now_iso', '_pricemaster_parse_decimal', '_pricemaster_record_change',
        '_pricemaster_save_feed_job', '_pricemaster_touch_meta', '_pricemaster_update_feed_job',
        'api_pricemaster_bulk_update', 'api_pricemaster_ebay_verify', 'api_pricemaster_feed_status',
        'api_pricemaster_listings',
    ),
    'printing': (
        '_ensure_label_presets_table', 'add_to_print_queue', 'browser_print_barcode', 'clear_print_queue',
        'delete_label_preset', 'generate_barcode_api', 'get_label_presets', 'get_print_queue',
        'get_printer_config', 'get_printer_status', 'print_barcode_api', 'printer_label_designer_page',
        'printer_label_preview_api', 'printer_settings_page', 'remove_from_print_queue',
        'save_label_preset', 'save_printer_config', 'scan_bluetooth_devices', 'test_printer',
        'test_printer_sample', 'update_label_preset', 'wake_printer',
    ),
    'raw_bol': (
        'api_rawbol_backfill_retail', 'api_rawbol_delete_lot', 'api_rawbol_desync_all', 'api_rawbol_items',
        'api_rawbol_logs', 'api_rawbol_stats', 'api_rawbol_update_lot', 'api_rawbol_upload',
        'api_rawbol_view', 'api_sold_enrich_lot_numbers', 'api_sold_enrich_recent', 'extractor_upload',
    ),
    'returns': (
        '_normalize_return_text', '_return_signature_from_row', '_returns_calculate_state',
        '_returns_find_duplicate_ids', '_returns_group_ids_for_return', '_returns_query_events_for_ids',
        '_returns_recompute_group_state', '_returns_recompute_state_from_events', '_returns_row_value',
        '_returns_status_from_row', 'api_create_return', 'api_delete_return', 'api_get_return_history',
        'api_get_returns', 'api_mark_return_received', 'api_relist_return', 'api_resold_return',
        'api_restart_return_lifecycle', 'api_restock_return', 'api_sync_amazon_returns',
        'api_sync_ebay_returns', 'api_undo_last_return_event', 'api_update_return', 'returns_page',
    ),
    'runtime': (
        'app', 'cache',
    ),
    'sales': (
        'get_sold_orders_route', 'sold_orders',
    ),
    'sales_actions': (
        'mark_order_handled', 'mark_order_unhandled',
    ),
    'sales_repair': (
        'allow_automatic_removal', 'cancel_automatic_removal', 'debug_sold_order',
        'debug_sold_order_by_barcode', 'find_inventory_for_sold', 'get_pending_removals',
        'get_sold_removal_history', 'manual_remove_sold_inventory', 'match_barcode_to_sold',
        'repair_missing_removals', 'reset_sold_order', 'trigger_automatic_removal',
    ),
    'server': (
        'start_flask', 'start_tunnel',
    ),
    'server_metrics': (
        '_SERVER_METRICS_DB_NAME', '_collect_server_metrics_snapshot', '_ensure_server_metrics_schema',
        '_record_server_metrics_snapshot', '_server_metrics_cpu_percent', '_server_metrics_cpu_temp_c',
        '_server_metrics_disk_stats', '_server_metrics_env_int', '_server_metrics_memory_stats',
        '_server_metrics_thread_started', '_start_server_metrics_history_thread',
        'server_metrics_history_worker',
    ),
    'shelf_assets': (
        '_GARAGE_AREA_DIR', '_GARAGE_BASES_DIR', '_GARAGE_MAP_DIR', '_GARAGE_ORIGINALS_DIR',
        '_GARAGE_PREVIEW_BASE_PAT', '_GARAGE_SHELF_PAT', '_GARAGE_SHELF_PICS_DIR', '_HALLWAY_AREA_DIR',
        '_HALLWAY_MAP_DIR', '_HALLWAY_ORIGINALS_DIR', '_HALLWAY_SHELF_PAT', '_HALLWAY_SHELF_PICS_DIR',
        '_LEGACY_GARAGE_BASES_DIR', '_LEGACY_GARAGE_MAP_DIR', '_LEGACY_GARAGE_SHELF_PICS_DIR',
        '_LEGACY_HALLWAY_MAP_DIR', '_LEGACY_HALLWAY_SHELF_PICS_DIR', '_LEGACY_MAPS_DIR',
        '_LEGACY_MARKED_DIR', '_LEGACY_MISC_MAP_DIR', '_LEGACY_MISC_SHELF_PICS_DIR',
        '_LEGACY_OFFICE_BASES_DIR', '_LEGACY_OFFICE_MAP_DIR', '_LEGACY_OFFICE_SHELF_PICS_DIR',
        '_LEGACY_SHELF_ORIGINALS_DIR', '_MISC_AREA_DIR', '_MISC_MAP_DIR', '_MISC_ORIGINALS_DIR',
        '_MISC_SHELF_PAT', '_MISC_SHELF_PICS_DIR', '_OFFICE_AREA_DIR', '_OFFICE_BASES_DIR',
        '_OFFICE_MAP_DIR', '_OFFICE_ORIGINALS_DIR', '_OFFICE_PREVIEW_BASE_PAT', '_OFFICE_SHELF_PAT',
        '_OFFICE_SHELF_PICS_DIR', '_SHELF_CODE_INPUT_RE', '_SHELF_ROOT_DIR', '_add_unique_path',
        '_area_storage_dir', '_delete_preview_base_image', '_iter_shelf_display_files',
        '_legacy_preview_base_path_for_code', '_original_shelf_image_path_for_code',
        '_preferred_shelf_display_dir', '_preview_base_lookup_codes', '_preview_base_path_candidates',
        '_preview_base_path_for_code', '_rename_preview_base_image', '_resolve_exact_shelf_display_path',
        '_resolve_exact_shelf_original_path', '_resolve_preview_base_path', '_resolve_shelf_display_path',
        '_resolve_shelf_original_path', '_safe_shelf_lookup_code', '_save_uploaded_shelf_png',
        '_shelf_area_for_code', '_shelf_code_exists', '_shelf_display_path_candidates',
        '_shelf_exact_display_path_candidates', '_shelf_exact_original_path_candidates',
        '_shelf_original_path_candidates', '_sync_original_to_preview_base', '_sync_preview_base_image',
        '_truthy_form_value', '_validate_shelf_code_input', 'shelf_base_image', 'shelf_image',
        'shelf_original',
    ),
    'shelves': (
        'api_check_shelf_code', 'api_clear_shelf_inventory', 'api_create_group', 'api_create_shelf',
        'api_delete_group', 'api_delete_shelf', 'api_duplicate_shelf', 'api_get_groups', 'api_list_shelves',
        'api_location_hierarchy', 'api_move_shelves', 'api_shelf_counts', 'api_update_shelf',
        'api_upload_shelf', 'api_valid_shelves', 'ensure_shelf_groups_table',
    ),
    'shipping_identity': (
        '_READY_TO_SHIP_ADDRESS_TOKEN_ALIASES', '_READY_TO_SHIP_STATE_CODES', '_READY_TO_SHIP_STATE_NAMES',
        '_READY_TO_SHIP_STREET_GENERIC_TOKENS', '_apply_ready_to_ship_note_payload',
        '_barcode_base_without_suffix', '_ensure_order_finder_matches_table',
        '_ensure_order_removal_allocations_table', '_ensure_ready_to_ship_notes_table',
        '_ensure_ready_to_ship_order_labels_table', '_ensure_ready_to_ship_unmatched_labels_table',
        '_is_exact_traced_suffixed_sold_order', '_load_order_finder_match_lookup',
        '_load_ready_to_ship_label_lookup', '_load_ready_to_ship_note_lookup',
        '_ready_to_ship_address_norm', '_ready_to_ship_attach_label', '_ready_to_ship_delete_label_file',
        '_ready_to_ship_extract_pdf_text', '_ready_to_ship_find_label_match', '_ready_to_ship_get_note_row',
        '_ready_to_ship_get_order_label_rows', '_ready_to_ship_image_value',
        '_ready_to_ship_insert_unmatched_label', '_ready_to_ship_items_to_list_stats_for_barcode',
        '_ready_to_ship_label_dir', '_ready_to_ship_label_match_score', '_ready_to_ship_label_path',
        '_ready_to_ship_label_payload', '_ready_to_ship_legacy_label_row', '_ready_to_ship_match_compact',
        '_ready_to_ship_match_norm', '_ready_to_ship_note_payload', '_ready_to_ship_order_label_payload',
        '_ready_to_ship_payload_for_order', '_ready_to_ship_rawbol_image',
        '_ready_to_ship_rawbol_total_qty_for_barcode', '_ready_to_ship_row_value',
        '_ready_to_ship_save_uploaded_label_file', '_ready_to_ship_sold_count_for_barcode',
        '_ready_to_ship_state_variants', '_ready_to_ship_sync_legacy_label_columns',
        '_ready_to_ship_unmatched_label_payload', '_ready_to_ship_warehouse_qty_for_barcode', 'code',
        'name',
    ),
    'shipping_labels': (
        '_LABELMASTER_REQUIRED_SETTINGS', '_labelmaster_amazon_decode_label',
        '_labelmaster_amazon_ship_from', '_labelmaster_buy_amazon', '_labelmaster_buy_ebay',
        '_labelmaster_collect_scope_tokens', '_labelmaster_ebay_error_message', '_labelmaster_ebay_request',
        '_labelmaster_ebay_scope_state', '_labelmaster_ebay_ship_from', '_labelmaster_find_order',
        '_labelmaster_get_settings', '_labelmaster_init_label_tables', '_labelmaster_latest_label',
        '_labelmaster_missing_settings', '_labelmaster_package_dims', '_labelmaster_package_weight',
        '_labelmaster_pick_cheapest_rate', '_labelmaster_resolve_amazon_address', '_labelmaster_safe_name',
        '_labelmaster_store_label', '_labelmaster_validate_package', 'api_labelmaster_buy',
        'api_labelmaster_get_settings', 'api_labelmaster_label_file', 'api_labelmaster_orders',
        'api_labelmaster_print', 'api_labelmaster_save_settings', 'api_labelmaster_status',
    ),
    'shipping_orders': (
        '_READY_TO_SHIP_CACHE_DAYS', '_invalidate_ready_to_ship_cache', '_ready_to_ship_poll_state',
        'get_order', 'ready_to_ship_clear_location', 'ready_to_ship_count',
        'ready_to_ship_delete_all_labels', 'ready_to_ship_delete_label', 'ready_to_ship_delete_order_label',
        'ready_to_ship_delete_unmatched_label', 'ready_to_ship_label_file', 'ready_to_ship_label_print',
        'ready_to_ship_location_options', 'ready_to_ship_order_label_file',
        'ready_to_ship_order_label_print', 'ready_to_ship_order_stats', 'ready_to_ship_save_note',
        'ready_to_ship_unmatched_label_file', 'ready_to_ship_unmatched_label_print',
        'ready_to_ship_unmatched_labels', 'ready_to_ship_upload_label', 'ready_to_ship_upload_labels_bulk',
    ),
    'sync': (
        '_start_auto_sync_thread', '_sync_manager_overdue_alert', '_sync_status_parse_timestamp',
        'auto_sync_worker', 'fix_amazon_barcodes', 'get_sync_status', 'recover_corrupted_upcs_api',
        'save_sync_settings', 'sync_all', 'sync_amazon_listings_api', 'sync_amazon_orders_api',
        'sync_amazon_upcs_api', 'sync_debug', 'sync_ebay_listings_api', 'sync_ebay_orders_api',
        'sync_missing_upcs', 'update_sync_timestamp',
    ),
    'telegram': (
        '_TELEGRAM_TOKEN_STATUS_CACHE', '_TELEGRAM_TOKEN_STATUS_CACHE_LOCK',
        '_api_alert_failure_is_confirmed', '_api_credential_age_issue', '_api_status_probe',
        '_collect_api_issue_alert', '_ensure_telegram_tables', '_generate_api_issue_text',
        '_start_telegram_alert_thread', '_start_telegram_command_thread',
        '_telegram_alert_state_mark_notified', '_telegram_alert_state_update',
        '_telegram_alert_thread_started', '_telegram_api_base', '_telegram_api_status_text',
        '_telegram_authorized_chat_ids', '_telegram_backup_log_result', '_telegram_backup_status',
        '_telegram_backup_status_text', '_telegram_collect_recipient_rows', '_telegram_command_response',
        '_telegram_command_thread_started', '_telegram_disable_notification_value',
        '_telegram_format_age_hours', '_telegram_get_bot_token', '_telegram_get_config_value',
        '_telegram_latest_backup_file', '_telegram_metric_line', '_telegram_normalize_command',
        '_telegram_parse_interval_minutes', '_telegram_recent_metric_summary', '_telegram_recipient_label',
        '_telegram_recipient_value', '_telegram_register_commands', '_telegram_send_alert_to_recipients',
        '_telegram_send_message', '_telegram_send_server_events', '_telegram_server_monitor_events',
        '_telegram_set_config_value', '_telegram_signature_event_ready', '_telegram_store_recent_chat',
        '_telegram_subscription_targets', '_telegram_system_uptime', '_telegram_token_statuses',
        'api_telegram_recent_chats', 'api_telegram_send_api_issue', 'api_telegram_send_health',
        'api_telegram_send_inventory', 'api_telegram_send_sync_overdue', 'api_telegram_send_test',
        'api_telegram_settings', 'telegram_alert_worker', 'telegram_command_worker', 'telegram_page',
    ),
    'warehouse_allocations': (
        '_check_requested_lot_mismatch', '_has_multiple_lot_rows', '_items_prep_items_to_list_url',
        '_items_prep_overage_payload', '_load_order_removal_allocations', '_lot_mismatch_payload',
        '_preferred_lot_from_request', '_request_lot_scope_is_all', '_resolve_action_lot_assignment',
        '_resolve_bol_lot_for_upc', '_resolve_prep_status_lot', '_save_order_removal_allocations',
        '_select_canonical_bol_row', '_select_prep_status_row',
    ),
    'warehouse_locations': (
        '_fba_macy_bol_lookup', '_get_table_and_pk', '_movelocation_barcode_key',
        '_movelocation_barcode_variants', '_movelocation_parse_qty', '_movelocation_pick_image',
        '_movelocation_row_location', 'api_fba_prep_location_family', 'api_location_items',
        'api_lookup_location', 'api_move_location', 'api_movelocation_bulk_cleanup',
        'api_movelocation_execute', 'api_movelocation_lookup', 'api_movelocation_lookup_shelf',
        'api_set_rack_location', 'api_update_row',
    ),
    'warehouse_maps': (
        'SHELF_COORDS', 'highlight', 'load_image_efficiently', 'pictureposition_page', 'searchrack_page',
        'set_pictureposition_path', 'show_inventory', 'upload_position_picture',
    ),
    'warehouse_matching': (
        '_clear_searchrack_row_location', '_effective_sold_order_barcode',
        '_ensure_order_processing_claim_column', '_group_searchrack_matches_by_location',
        '_is_order_processing_claim_stale', '_items_prep_delete_legacy_inventory_entry',
        '_prep_history_inventory_bucket_for_upc', '_prep_history_inventory_fallback',
        '_prep_select_inventory_match', '_ready_to_ship_condition_is_new',
        '_ready_to_ship_match_display_location', '_ready_to_ship_match_location_equals',
        '_ready_to_ship_rank_inventory_matches', '_ready_to_ship_resolve_searchrack_location_match',
        '_ready_to_ship_searchrack_match_by_id', '_ready_to_ship_searchrack_match_from_row',
        '_ready_to_ship_suffix_alternatives', '_ready_to_ship_suffix_inventory_matches',
        '_ready_to_ship_valid_requested_match', '_ready_to_ship_valid_suffix_suggestion',
        '_searchrack_matches_for_barcode', '_searchrack_matches_for_removal_context',
        '_searchrack_removal_schema', '_searchrack_total_qty_for_key', '_serialize_prep_location_entry',
        '_sold_location_key', '_sold_location_label', '_sold_order_value', '_sold_removal_barcode_key',
        '_sold_removal_barcode_variants',
    ),
    'warehouse_receiving': (
        '_add_item_screening_lookup', '_clean_warehouse_note', '_ensure_custom_item_registry',
        '_load_add_item_warehouse_notes', '_next_warehouse_note_suffix',
        '_warehouse_note_existing_suffixes', 'additem_multi_page', 'additem_page', 'additemtrue',
        'api_add_item_screen', 'barcode_page', 'fba_labels_page', 'fba_prep_page', 'finalize_barcodes',
        'generate_custom_barcode', 'get_high_res_image_url', 'item_prep_create_item_page',
        'movelocation_page', 'multibarcode_page', 'pictures_page', 'position_diagnostic', 'position_page',
        'process_barcode', 'process_position', 'save_custom_item_identity', 'save_temp_item', 'toggle',
    ),
    'warehouse_search': (
        '_search_all_cache', '_search_cache_timeout', 'api_bol_stats', 'api_bol_stats_auto_assigned',
        'api_get_lot_numbers', 'api_search_all', 'api_search_db', 'searchbol_api', 'searchrack_api',
        'unified_search_page', 'update_item', 'view_all',
    ),
    'web_hooks': (
        '_I18N_CACHE_V', '_I18N_SRC_PAT', 'add_no_cache_headers', 'inject_server_info',
    ),
}
SYMBOL_MODULES = {name: module for module, names in EXPORT_GROUPS.items() for name in names}

# Names historically re-exported by app.py for maintenance scripts.
IMPORT_EXPORTS = {
    'math': ('math', None),
    'collect_token_statuses': ('token_expiry', 'collect_token_statuses'),
    'expiring_token_reminders': ('token_expiry', 'expiring_token_reminders'),
    'format_token_statuses': ('token_expiry', 'format_token_statuses'),
    'reduce_missing_plan_quantity': ('fba_inbound', 'reduce_missing_plan_quantity'),
    'remap_recovery_boxes': ('fba_inbound', 'remap_recovery_boxes'),
    'Cache': ('flask_caching', 'Cache'),
    'Compress': ('flask_compress', 'Compress'),
    'Decimal': ('decimal', 'Decimal'),
    'ET': ('xml.etree.ElementTree', None),
    'FbaInboundValidationError': ('fba_inbound', 'FbaInboundValidationError'),
    'Flask': ('flask', 'Flask'),
    'Image': ('PIL', 'Image'),
    'ImageDraw': ('PIL', 'ImageDraw'),
    'ImageFont': ('PIL', 'ImageFont'),
    'ImageOps': ('PIL', 'ImageOps'),
    'InvalidOperation': ('decimal', 'InvalidOperation'),
    'MIMEMultipart': ('email.mime.multipart', 'MIMEMultipart'),
    'MIMEText': ('email.mime.text', 'MIMEText'),
    'Path': ('pathlib', 'Path'),
    'ROUND_HALF_UP': ('decimal', 'ROUND_HALF_UP'),
    'RequestEntityTooLarge': ('werkzeug.exceptions', 'RequestEntityTooLarge'),
    'US_MARKETPLACE_ID': ('fba_inbound', 'US_MARKETPLACE_ID'),
    '_re': ('re', None),
    '_register_listing_mapping': ('listing_mapping_routes', 'register'),
    'addToSearchRack': ('DBmanager', 'addToSearchRack'),
    'amazonStoreDB': ('DBmanager', 'amazonStoreDB'),
    'apply_owner_corrections_from_amazon_error': ('fba_inbound', 'apply_owner_corrections_from_amazon_error'),
    'base64': ('base64', None),
    'build_create_plan_request': ('fba_inbound', 'build_create_plan_request'),
    'build_item_label_job': ('fba_inbound', 'build_item_label_job'),
    'build_set_packing_request': ('fba_inbound', 'build_set_packing_request'),
    'build_transportation_request': ('fba_inbound', 'build_transportation_request'),
    'builtins': ('builtins', None),
    'connect_db': ('DBmanager', 'connect_db'),
    'contextmanager': ('contextlib', 'contextmanager'),
    'createSearchRackDB': ('DBmanager', 'createSearchRackDB'),
    'datetime': ('datetime', None),
    'decode_header': ('email.header', 'decode_header'),
    'ebayStoreDB': ('DBmanager', 'ebayStoreDB'),
    'ebay_mapping': ('ebay_mapping', None),
    'email': ('email', None),
    'enrich_searchrack_db': ('DBmanager', 'enrich_searchrack_db'),
    'ensure_sold_orders_schema': ('DBmanager', 'ensure_sold_orders_schema'),
    'find_item': ('inventory', 'find_item'),
    'get_access_token': ('token_manager', 'get_access_token'),
    'gzip': ('gzip', None),
    'has_app_context': ('flask', 'has_app_context'),
    'hashlib': ('hashlib', None),
    'html': ('html', None),
    'imaplib': ('imaplib', None),
    'io': ('io', None),
    'is_expired': ('token_manager', 'is_expired'),
    'json': ('json', None),
    'jsonify': ('flask', 'jsonify'),
    'load_dotenv': ('dotenv', 'load_dotenv'),
    'load_tokens': ('token_manager', 'load_tokens'),
    'logging': ('logging', None),
    'make_response': ('flask', 'make_response'),
    'minidom': ('xml.dom.minidom', None),
    'missing_source_address_fields': ('fba_inbound', 'missing_source_address_fields'),
    'normalize_box_drafts': ('fba_inbound', 'normalize_box_drafts'),
    'normalize_source_address': ('fba_inbound', 'normalize_source_address'),
    'nullcontext': ('contextlib', 'nullcontext'),
    'option_state': ('fba_inbound', 'option_state'),
    'os': ('os', None),
    'parseaddr': ('email.utils', 'parseaddr'),
    'parsedate_to_datetime': ('email.utils', 'parsedate_to_datetime'),
    'policy': ('email', 'policy'),
    'printer_manager': ('printer_manager', 'printer_manager'),
    'pytz': ('pytz', None),
    'random': ('random', None),
    're': ('re', None),
    'redirect': ('flask', 'redirect'),
    'render_template': ('flask', 'render_template'),
    'request': ('flask', 'request'),
    'requests': ('requests', None),
    'resolve_barcode_from_marketplace_sku': ('DBmanager', 'resolve_barcode_from_marketplace_sku'),
    'secrets': ('secrets', None),
    'send_file': ('flask', 'send_file'),
    'session': ('flask', 'session'),
    'smtplib': ('smtplib', None),
    'sqlite3': ('sqlite3', None),
    'store_ebay_order': ('DBmanager', 'store_ebay_order'),
    'subprocess': ('subprocess', None),
    'summarize_money': ('fba_inbound', 'summarize_money'),
    'sys': ('sys', None),
    'threading': ('threading', None),
    'time': ('time', None),
    'url_for': ('flask', 'url_for'),
    'uuid': ('uuid', None),
    'validate_box_totals': ('fba_inbound', 'validate_box_totals'),
}


def resolve(name):
    owner = SYMBOL_MODULES.get(name)
    if owner is not None:
        return getattr(import_module(f"sweetshelves.{owner}"), name)
    if name in IMPORT_EXPORTS:
        module_name, attribute = IMPORT_EXPORTS[name]
        module = import_module(module_name)
        return getattr(module, attribute) if attribute else module
    raise AttributeError(f"module app has no attribute {name!r}")
