"""Register feature endpoints without changing existing URLs or endpoint names."""

import requests
from listing_mapping_routes import register as _register_listing_mapping
from token_manager import get_access_token
from werkzeug.exceptions import RequestEntityTooLarge
from . import (
    amazon_catalog as ss_amazon_catalog, amazon_orders as ss_amazon_orders, amazon_publish as
    ss_amazon_publish, analytics as ss_analytics, bol_inventory as ss_bol_inventory, bulk_manifest as
    ss_bulk_manifest, cache_admin as ss_cache_admin, caching as ss_caching, database as ss_database,
    diagnostics as ss_diagnostics, ebay_auth as ss_ebay_auth, ebay_catalog as ss_ebay_catalog,
    ebay_policies as ss_ebay_policies, ebay_publish as ss_ebay_publish, email_settings as
    ss_email_settings, enrichment as ss_enrichment, errors as ss_errors, facebook as ss_facebook,
    fba_readiness as ss_fba_readiness, fba_scanning as ss_fba_scanning, fba_sessions as ss_fba_sessions,
    fba_shipments as ss_fba_shipments, finder as ss_finder, inventory_alerts as ss_inventory_alerts,
    inventory_archives as ss_inventory_archives, inventory_cleanup as ss_inventory_cleanup,
    inventory_history_views as ss_inventory_history_views, listing_alerts as ss_listing_alerts,
    listing_lifecycle as ss_listing_lifecycle, listing_log as ss_listing_log, listing_queue as
    ss_listing_queue, listing_settings as ss_listing_settings, mail_center as ss_mail_center,
    marketplace_sales as ss_marketplace_sales, pages as ss_pages, payouts as ss_payouts, prep_actions as
    ss_prep_actions, prep_context as ss_prep_context, prep_diagnostics as ss_prep_diagnostics,
    prep_locations as ss_prep_locations, prep_log as ss_prep_log, prep_media as ss_prep_media, prep_undo
    as ss_prep_undo, prep_views as ss_prep_views, pricing as ss_pricing, printing as ss_printing, raw_bol
    as ss_raw_bol, returns as ss_returns, runtime as ss_runtime, sales as ss_sales, sales_actions as
    ss_sales_actions, sales_repair as ss_sales_repair, shelf_assets as ss_shelf_assets, shelves as
    ss_shelves, shipping_labels as ss_shipping_labels, shipping_orders as ss_shipping_orders, sync as
    ss_sync, telegram as ss_telegram, warehouse_locations as ss_warehouse_locations, warehouse_maps as
    ss_warehouse_maps, warehouse_receiving as ss_warehouse_receiving, warehouse_search as
    ss_warehouse_search, web_hooks as ss_web_hooks,
)


def register_routes():
    ss_runtime.app.teardown_appcontext(ss_database.close_db_connections)
    ss_runtime.app.route('/api/data_version')(ss_caching.api_data_version)
    ss_runtime.app.context_processor(ss_web_hooks.inject_server_info)
    ss_runtime.app.route('/shelf-image/<path:code>.png')(ss_shelf_assets.shelf_image)
    ss_runtime.app.route('/shelf-original/<path:code>.png')(ss_shelf_assets.shelf_original)
    ss_runtime.app.route('/shelf-base/<path:code>.png')(ss_shelf_assets.shelf_base_image)
    ss_runtime.app.after_request(ss_web_hooks.add_no_cache_headers)
    ss_runtime.app.route('/tools')(ss_pages.tools)
    ss_runtime.app.route('/prep-media-cleaner')(ss_pages.prep_media_cleaner_page)
    ss_runtime.app.route('/bulk-manifest')(ss_bulk_manifest.bulk_manifest_page)
    ss_runtime.app.route('/bulk-manifest/<int:manifest_id>/pictures')(ss_bulk_manifest.bulk_manifest_pictures_page)
    ss_runtime.app.route('/api/bulk-manifest/lookup', methods=['GET'])(ss_bulk_manifest.api_bulk_manifest_lookup)
    ss_runtime.app.route('/api/bulk-manifest/search', methods=['GET'])(ss_bulk_manifest.api_bulk_manifest_search)
    ss_runtime.app.route('/api/bulk-manifest/create', methods=['POST'])(ss_bulk_manifest.api_bulk_manifest_create)
    ss_runtime.app.route('/api/bulk-manifest/<int:manifest_id>/update', methods=['POST'])(ss_bulk_manifest.api_bulk_manifest_update)
    ss_runtime.app.route('/api/bulk-manifest/refresh', methods=['POST'])(ss_bulk_manifest.api_bulk_manifest_refresh)
    ss_runtime.app.route('/api/bulk-manifest/history', methods=['GET'])(ss_bulk_manifest.api_bulk_manifest_history)
    ss_runtime.app.route('/api/bulk-manifest/<int:manifest_id>', methods=['GET'])(ss_bulk_manifest.api_bulk_manifest_detail)
    ss_runtime.app.route('/api/bulk-manifest/<int:manifest_id>/delete', methods=['POST', 'DELETE'])(ss_bulk_manifest.api_bulk_manifest_delete)
    ss_runtime.app.route('/api/bulk-manifest/<int:manifest_id>/photos', methods=['GET'])(ss_bulk_manifest.api_bulk_manifest_photos)
    ss_runtime.app.route('/api/bulk-manifest/<int:manifest_id>/photos', methods=['POST'])(ss_bulk_manifest.api_bulk_manifest_add_photos)
    ss_runtime.app.route('/api/bulk-manifest/<int:manifest_id>/google-sheet', methods=['GET', 'POST'])(ss_bulk_manifest.api_bulk_manifest_google_sheet)
    ss_runtime.app.route('/api/bulk-manifest/<int:manifest_id>/google-sheet-delete', methods=['POST', 'DELETE'])(ss_bulk_manifest.api_bulk_manifest_google_sheet_delete)
    ss_runtime.app.route('/api/bulk-manifest/<int:manifest_id>/google-sheet-status', methods=['GET'])(ss_bulk_manifest.api_bulk_manifest_google_sheet_status)
    ss_runtime.app.route('/api/bulk-manifest/google-sheet-health', methods=['GET'])(ss_bulk_manifest.api_bulk_manifest_google_sheet_health)
    ss_runtime.app.route('/api/bulk-manifest/<int:manifest_id>/mark-sold', methods=['POST'])(ss_bulk_manifest.api_bulk_manifest_mark_sold)
    ss_runtime.app.route('/api/bulk-manifest/cleanup-items', methods=['GET'])(ss_bulk_manifest.api_bulk_manifest_cleanup_items)
    ss_runtime.app.route('/listingagent')(ss_listing_settings.listingagent)
    ss_runtime.app.route('/listingagent/mobile')(ss_listing_settings.listingagent_mobile)
    ss_runtime.app.route('/check-items')(ss_listing_settings.check_items)
    ss_runtime.app.route('/items-to-list/mobile-photos')(ss_listing_settings.items_to_list_mobile_photos)
    ss_runtime.app.route('/api/listingagent/settings', methods=['GET'])(ss_listing_settings.api_listingagent_get_settings)
    ss_runtime.app.route('/api/listingagent/settings', methods=['POST'])(ss_listing_settings.api_listingagent_save_settings)
    ss_runtime.app.route('/api/listingagent/working_draft', methods=['GET'])(ss_listing_settings.api_listingagent_get_working_draft)
    ss_runtime.app.route('/api/listingagent/working_draft', methods=['POST'])(ss_listing_settings.api_listingagent_save_working_draft)
    ss_runtime.app.route('/api/listingagent/working_draft', methods=['DELETE'])(ss_listing_settings.api_listingagent_delete_working_draft)
    ss_runtime.app.route('/api/listingagent/check_request', methods=['GET'])(ss_listing_settings.api_listingagent_check_request_get)
    ss_runtime.app.route('/api/listingagent/check_request', methods=['POST'])(ss_listing_settings.api_listingagent_check_request_save)
    ss_runtime.app.route('/api/listingagent/check_request/complete', methods=['POST'])(ss_listing_settings.api_listingagent_check_request_complete)
    ss_runtime.app.route('/api/listingagent/check_requests', methods=['GET'])(ss_listing_settings.api_listingagent_check_requests)
    ss_runtime.app.route('/api/listingagent/check_notes', methods=['GET'])(ss_listing_settings.api_listingagent_check_notes_get)
    ss_runtime.app.route('/api/listingagent/check_notes', methods=['POST'])(ss_listing_settings.api_listingagent_check_notes_add)
    ss_runtime.app.route('/api/listingagent/check_media', methods=['GET'])(ss_listing_settings.api_listingagent_check_media_get)
    ss_runtime.app.route('/api/listingagent/check_media/upload', methods=['POST'])(ss_listing_settings.api_listingagent_check_media_upload)
    ss_runtime.app.route('/api/listingagent/queue', methods=['GET'])(ss_listing_settings.api_listingagent_queue)
    ss_runtime.app.route('/api/listingagent/queue/statuses', methods=['POST'])(ss_listing_settings.api_listingagent_queue_statuses)
    ss_runtime.app.route('/api/listingagent/queue/add', methods=['POST'])(ss_listing_settings.api_listingagent_queue_add)
    ss_runtime.app.route('/api/listingagent/queue/mark_listed', methods=['POST'])(ss_listing_settings.api_listingagent_queue_mark_listed)
    ss_runtime.app.route('/api/listingagent/queue/remove', methods=['POST'])(ss_listing_settings.api_listingagent_queue_remove)
    ss_runtime.app.route('/listing-log')(ss_listing_log.page_listing_log)
    ss_runtime.app.route('/api/listinglog/recent', methods=['GET'])(ss_listing_log.api_listinglog_recent)
    ss_runtime.app.route('/api/preplog/recent', methods=['GET'])(ss_prep_log.api_preplog_recent)
    ss_runtime.app.route('/api/preplog/update', methods=['POST'])(ss_prep_log.api_preplog_update)
    ss_runtime.app.route('/api/preplog/undo', methods=['POST'])(ss_prep_log.api_preplog_undo)
    ss_runtime.app.route('/api/preplog/reassign_lot', methods=['POST'])(ss_prep_log.api_preplog_reassign_lot)
    ss_runtime.app.route('/api/listingagent/photos', methods=['GET'])(ss_listing_queue.api_listingagent_photos_get)
    ss_runtime.app.route('/api/listingagent/photos/upload', methods=['POST'])(ss_listing_queue.api_listingagent_photos_upload)
    ss_runtime.app.route('/api/listingagent/live_listings/search', methods=['GET'])(ss_listing_queue.api_listingagent_live_listings_search)
    ss_runtime.app.route('/api/listingagent/upc/search', methods=['GET'])(ss_listing_queue.api_listingagent_upc_search)
    ss_runtime.app.route('/api/listingagent/upc/<upc>', methods=['GET'])(ss_listing_queue.api_listingagent_upc_detail)
    ss_runtime.app.route('/api/listingagent/ebay/locations', methods=['GET'])(ss_ebay_policies.api_listingagent_ebay_locations)
    ss_runtime.app.route('/api/listingagent/ebay/business_policies', methods=['GET'])(ss_ebay_policies.api_listingagent_ebay_business_policies)
    ss_runtime.app.route('/api/listingagent/ebay/offers_for_sku', methods=['GET'])(ss_ebay_policies.api_listingagent_ebay_offers_for_sku)
    ss_runtime.app.route('/api/listingagent/ebay/comps', methods=['GET'])(ss_ebay_catalog.api_listingagent_ebay_comps)
    ss_runtime.app.route('/api/listingagent/ebay/category_suggestions', methods=['GET'])(ss_ebay_catalog.api_listingagent_ebay_category_suggestions)
    ss_runtime.app.route('/api/listingagent/ebay/category_aspects', methods=['GET'])(ss_ebay_catalog.api_listingagent_ebay_category_aspects)
    ss_runtime.app.route('/api/listingagent/ebay/catalog_search', methods=['GET'])(ss_ebay_catalog.api_listingagent_ebay_catalog_search)
    ss_runtime.app.route('/api/listingagent/ebay/product_specifics', methods=['GET'])(ss_ebay_catalog.api_listingagent_ebay_product_specifics)
    ss_runtime.app.route('/api/listingagent/ebay/catalog_item', methods=['GET'])(ss_ebay_catalog.api_listingagent_ebay_catalog_item)
    ss_runtime.app.route('/api/listingagent/ebay/generate_description', methods=['POST'])(ss_ebay_publish.api_listingagent_ebay_generate_description)
    ss_runtime.app.route('/api/listingagent/ebay/generate_title', methods=['POST'])(ss_ebay_publish.api_listingagent_ebay_generate_title)
    ss_runtime.app.route('/api/listingagent/ebay/draft', methods=['POST'])(ss_ebay_publish.api_listingagent_ebay_draft)
    ss_ebay_publish._publish_mapped_ebay_listing = _register_listing_mapping(
        ss_runtime.app, db_connection=ss_database.db_connection, get_token=lambda: get_access_token(),
        post=lambda *args, **kwargs: requests.post(*args, **kwargs),
        build_draft=lambda *args, **kwargs: ss_ebay_publish._listingagent_ebay_create_draft_offer(*args, **kwargs),
        ebay_request=lambda *args, **kwargs: ss_ebay_policies._ebay_api_request(*args, **kwargs),
        mark_listed=lambda *args, **kwargs: ss_listing_queue._listagent_mark_listed(*args, **kwargs),
        mark_bol=lambda *args, **kwargs: ss_listing_lifecycle._listing_center_mark_bol_listed(*args, **kwargs),
        safe_error=lambda *args, **kwargs: ss_errors._safe_error(*args, **kwargs))
    ss_runtime.app.route('/api/listingagent/ebay/publish', methods=['POST'])(ss_ebay_publish.api_listingagent_ebay_publish)
    ss_runtime.app.route('/api/listingagent/amazon/account_check', methods=['GET'])(ss_amazon_catalog.api_listingagent_amazon_account_check)
    ss_runtime.app.route('/api/listingagent/amazon/restriction_check', methods=['GET'])(ss_amazon_catalog.api_listingagent_amazon_restriction_check)
    ss_runtime.app.route('/api/listingagent/amazon/catalog_search', methods=['GET'])(ss_amazon_catalog.api_listingagent_amazon_catalog_search)
    ss_runtime.app.route('/api/listingagent/amazon/catalog_item', methods=['GET'])(ss_amazon_catalog.api_listingagent_amazon_catalog_item)
    ss_runtime.app.route('/api/listingagent/amazon/listing', methods=['GET'])(ss_amazon_catalog.api_listingagent_amazon_get_listing)
    ss_runtime.app.route('/api/listingagent/amazon/put_offer', methods=['POST'])(ss_amazon_publish.api_listingagent_amazon_put_offer)
    ss_runtime.app.route('/emailer')(ss_email_settings.emailer)
    ss_runtime.app.route('/api/emailer/settings', methods=['GET'])(ss_email_settings.get_emailer_settings)
    ss_runtime.app.route('/api/emailer/settings', methods=['POST'])(ss_email_settings.save_emailer_settings)
    ss_runtime.app.route('/api/emailer/send-test', methods=['POST'])(ss_email_settings.send_test_email)
    ss_runtime.app.route('/api/emailer/send-test-inventory', methods=['POST'])(ss_email_settings.send_test_inventory_email)
    ss_runtime.app.route('/api/emailer/send-health', methods=['POST'])(ss_email_settings.send_health_email)
    ss_runtime.app.route('/api/emailer/send-inventory', methods=['POST'])(ss_inventory_alerts.send_inventory_alert_email)
    ss_runtime.app.route('/telegram')(ss_telegram.telegram_page)
    ss_runtime.app.route('/api/telegram/settings', methods=['GET', 'POST'])(ss_telegram.api_telegram_settings)
    ss_runtime.app.route('/api/telegram/recent-chats', methods=['GET'])(ss_telegram.api_telegram_recent_chats)
    ss_runtime.app.route('/api/telegram/send-test', methods=['POST'])(ss_telegram.api_telegram_send_test)
    ss_runtime.app.route('/api/telegram/send-inventory', methods=['POST'])(ss_telegram.api_telegram_send_inventory)
    ss_runtime.app.route('/api/telegram/send-health', methods=['POST'])(ss_telegram.api_telegram_send_health)
    ss_runtime.app.route('/api/telegram/send-sync-overdue', methods=['POST'])(ss_telegram.api_telegram_send_sync_overdue)
    ss_runtime.app.route('/api/telegram/send-api-issue', methods=['POST'])(ss_telegram.api_telegram_send_api_issue)
    ss_runtime.app.route('/bol-stats')(ss_pages.bol_stats_page)
    ss_runtime.app.route('/barcode-print-que')(ss_pages.barcode_print_que)
    ss_runtime.app.route('/barcode-print-view')(ss_pages.barcode_print_view)
    ss_runtime.app.route('/sync')(ss_pages.sync)
    ss_runtime.app.route('/misc')(ss_pages.misc)
    ss_runtime.app.route('/financial-analytics')(ss_pages.financial_analytics)
    ss_runtime.app.route('/inventory-analytics')(ss_pages.inventory_seller_analytics)
    ss_runtime.app.route('/inventory-cleanup')(ss_pages.inventory_cleanup_decisions)
    ss_runtime.app.route('/api/inventory-cleanup', methods=['GET'])(ss_analytics.api_inventory_cleanup)
    ss_runtime.app.route('/api/inventory-age-summary', methods=['GET'])(ss_analytics.api_inventory_age_summary)
    ss_runtime.app.route('/api/inventory-age/rescan', methods=['POST'])(ss_analytics.api_inventory_age_rescan)
    ss_runtime.app.route('/api/inventory-seller-analytics', methods=['GET'])(ss_analytics.api_inventory_seller_analytics)
    ss_runtime.app.route('/api/financial-analytics')(ss_analytics.api_financial_analytics)
    ss_runtime.app.route('/api/amazon/financial-summary', methods=['GET'])(ss_analytics.api_amazon_financial_summary)
    ss_runtime.app.route('/api/refresh-sold-data', methods=['POST'])(ss_analytics.api_refresh_sold_data)
    ss_runtime.app.route('/api/warehouse/item-prep/<path:barcode>', methods=['GET'])(ss_prep_context.api_warehouse_item_prep_context)
    ss_runtime.app.route('/item-prep')(ss_prep_views.item_prep_page)
    ss_runtime.app.route('/item-prep/log')(ss_prep_views.item_prep_log_page)
    ss_runtime.app.route('/item-prep/diagnostic')(ss_prep_views.item_prep_diagnostic_page)
    ss_runtime.app.route('/item-prep/diagnostic/view')(ss_prep_views.item_prep_diagnostic_view_page)
    ss_runtime.app.route('/item-prep-no-barcode')(ss_prep_views.item_prep_no_barcode_page)
    ss_runtime.app.route('/api/search-rawbol', methods=['POST'])(ss_prep_views.search_rawbol_api)
    ss_runtime.app.route('/printer-settings')(ss_printing.printer_settings_page)
    ss_runtime.app.route('/printer-label-designer')(ss_printing.printer_label_designer_page)
    ss_runtime.app.route('/api/printer/config', methods=['GET'])(ss_printing.get_printer_config)
    ss_runtime.app.route('/api/printer/status', methods=['GET'])(ss_printing.get_printer_status)
    ss_runtime.app.route('/api/printer/config', methods=['POST'])(ss_printing.save_printer_config)
    ss_runtime.app.route('/api/printer/scan-bluetooth', methods=['POST'])(ss_printing.scan_bluetooth_devices)
    ss_runtime.app.route('/api/printer/wake', methods=['POST'])(ss_printing.wake_printer)
    ss_runtime.app.route('/api/printer/test', methods=['POST'])(ss_printing.test_printer)
    ss_runtime.app.route('/api/printer/test-sample', methods=['POST'])(ss_printing.test_printer_sample)
    ss_runtime.app.route('/api/printer/label-preview', methods=['POST'])(ss_printing.printer_label_preview_api)
    ss_runtime.app.route('/api/printer/print-barcode', methods=['POST'])(ss_printing.print_barcode_api)
    ss_runtime.app.route('/api/printer/browser-print', methods=['POST'])(ss_printing.browser_print_barcode)
    ss_runtime.app.route('/api/printer/generate-barcode', methods=['POST'])(ss_printing.generate_barcode_api)
    ss_runtime.app.route('/api/printer/label-presets', methods=['GET'])(ss_printing.get_label_presets)
    ss_runtime.app.route('/api/printer/label-presets', methods=['POST'])(ss_printing.save_label_preset)
    ss_runtime.app.route('/api/printer/label-presets/<int:preset_id>', methods=['PUT'])(ss_printing.update_label_preset)
    ss_runtime.app.route('/api/printer/label-presets/<int:preset_id>', methods=['DELETE'])(ss_printing.delete_label_preset)
    ss_runtime.app.route('/api/print-queue', methods=['GET'])(ss_printing.get_print_queue)
    ss_runtime.app.route('/api/print-queue', methods=['POST'])(ss_printing.add_to_print_queue)
    ss_runtime.app.route('/api/print-queue', methods=['DELETE'])(ss_printing.clear_print_queue)
    ss_runtime.app.route('/api/print-queue/item', methods=['DELETE'])(ss_printing.remove_from_print_queue)
    ss_runtime.app.route('/item-prep-create-item')(ss_warehouse_receiving.item_prep_create_item_page)
    ss_runtime.app.route('/api/items-prep/generate-barcode', methods=['POST'])(ss_warehouse_receiving.generate_custom_barcode)
    ss_runtime.app.route('/api/items-prep/temp-item', methods=['POST'])(ss_warehouse_receiving.save_temp_item)
    ss_runtime.app.route('/api/custom-item/identity', methods=['POST'])(ss_warehouse_receiving.save_custom_item_identity)
    ss_runtime.app.route('/api/clear_cache', methods=['GET'])(ss_caching.api_clear_cache)
    ss_runtime.app.route('/api/bol_lookup', methods=['GET'])(ss_prep_context.api_bol_lookup)
    ss_runtime.app.route('/api/items_prep/auto_assign_lot', methods=['POST'])(ss_prep_context.api_items_prep_auto_assign_lot)
    ss_runtime.app.route('/api/items_prep/status/<upc>', methods=['GET'])(ss_prep_actions.api_items_prep_status_get)
    ss_runtime.app.route('/api/items_prep/status', methods=['POST'])(ss_prep_actions.api_items_prep_status)
    ss_runtime.app.route('/api/items_prep/allocate_lots', methods=['POST'])(ss_prep_actions.api_items_prep_allocate_lots)
    ss_runtime.app.route('/api/items_prep/create_bad_entry', methods=['POST'])(ss_prep_actions.api_items_prep_create_bad_entry)
    ss_runtime.app.route('/api/items_prep/create_return_entry', methods=['POST'])(ss_prep_actions.api_items_prep_create_return_entry)
    ss_runtime.app.route('/api/items_prep/good_entries/<base_upc>', methods=['GET'])(ss_prep_actions.api_items_prep_good_entries)
    ss_runtime.app.route('/api/items_prep/cleanup_temp', methods=['POST'])(ss_prep_actions.api_items_prep_cleanup_temp)
    ss_runtime.app.route('/api/bol_items/quantity', methods=['POST'])(ss_prep_actions.api_bol_items_update_quantity)
    ss_runtime.app.route('/api/items_prep/status/<upc>', methods=['DELETE'])(ss_prep_actions.api_items_prep_status_delete)
    ss_runtime.app.route('/api/items_prep/undo', methods=['POST'])(ss_prep_undo.api_items_prep_undo)
    ss_runtime.app.route('/api/items_prep/history_entry/delete', methods=['POST'])(ss_prep_undo.api_items_prep_history_entry_delete)
    ss_runtime.app.route('/api/items_prep/diagnostic', methods=['POST'])(ss_prep_diagnostics.api_items_prep_diagnostic)
    ss_runtime.app.errorhandler(RequestEntityTooLarge)(ss_errors.handle_file_too_large)
    ss_runtime.app.route('/api/items_prep/diagnostic/<upc>', methods=['GET'])(ss_prep_diagnostics.api_items_prep_diagnostic_get)
    ss_runtime.app.route('/api/items_prep/diagnostic/<upc>/live_listings', methods=['GET'])(ss_prep_diagnostics.api_items_prep_diagnostic_live_listings)
    ss_runtime.app.route('/api/items_prep/diagnostic/<upc>/history', methods=['GET'])(ss_prep_diagnostics.api_items_prep_diagnostic_history)
    ss_runtime.app.route('/api/items_prep/diagnostic/<upc>/photos', methods=['DELETE'])(ss_prep_diagnostics.api_items_prep_diagnostic_delete_photos)
    ss_runtime.app.route('/api/items_prep/diagnostic/<upc>/photos', methods=['POST'])(ss_prep_diagnostics.api_items_prep_diagnostic_add_photos)
    ss_runtime.app.route('/api/items_prep/photo/<int:photo_id>', methods=['DELETE'])(ss_prep_diagnostics.api_items_prep_delete_photo)
    ss_runtime.app.route('/api/items_prep/set_display_image', methods=['POST'])(ss_prep_diagnostics.api_items_prep_set_display_image)
    ss_runtime.app.route('/api/items_prep/diagnostic/<upc>/trash', methods=['GET'])(ss_prep_diagnostics.api_items_prep_trash_list)
    ss_runtime.app.route('/api/items_prep/diagnostic/<upc>/trash/restore', methods=['POST'])(ss_prep_diagnostics.api_items_prep_trash_restore)
    ss_runtime.app.route('/api/items_prep/diagnostic/<upc>/reset', methods=['POST'])(ss_prep_diagnostics.api_items_prep_diagnostic_reset)
    ss_runtime.app.route('/shelfcreator')(ss_pages.shelfcreator)
    ss_runtime.app.route('/shelfmanager')(ss_pages.shelfmanager)
    ss_runtime.app.route('/extractor')(ss_pages.extractor)
    ss_runtime.app.route('/api/items_prep/notes/<upc>', methods=['GET'])(ss_prep_media.api_items_prep_notes_get)
    ss_runtime.app.route('/api/items_prep/notes', methods=['POST'])(ss_prep_media.api_items_prep_notes_add)
    ss_runtime.app.route('/api/items_prep/notes/<int:note_id>', methods=['DELETE'])(ss_prep_media.api_items_prep_notes_delete)
    ss_runtime.app.route('/api/items_prep/media/<upc>', methods=['GET'])(ss_prep_media.api_items_prep_media_get)
    ss_runtime.app.route('/api/items_prep/media/<upc>', methods=['POST'])(ss_prep_media.api_items_prep_media_add)
    ss_runtime.app.route('/api/items_prep/media/<int:media_id>', methods=['DELETE'])(ss_prep_media.api_items_prep_media_delete)
    ss_runtime.app.route('/api/prep-media-cleaner/overview', methods=['GET'])(ss_prep_media.api_prep_media_cleaner_overview)
    ss_runtime.app.route('/api/prep-media-cleaner/query', methods=['GET'])(ss_prep_media.api_prep_media_cleaner_query)
    ss_runtime.app.route('/api/prep-media-cleaner/delete', methods=['POST'])(ss_prep_media.api_prep_media_cleaner_delete)
    ss_runtime.app.route('/api/items_prep/location/<upc>', methods=['GET'])(ss_prep_locations.api_items_prep_location_get)
    ss_runtime.app.route('/api/items_prep/location', methods=['POST'])(ss_prep_locations.api_items_prep_location_set)
    ss_runtime.app.route('/api/items_prep/location/clear', methods=['POST'])(ss_prep_locations.api_items_prep_location_clear)
    ss_runtime.app.route('/api/items_prep/reset', methods=['POST'])(ss_prep_locations.api_items_prep_reset)
    ss_runtime.app.route('/items-to-list')(ss_pages.items_to_list_page)
    ss_runtime.app.route('/price-master')(ss_pages.price_master_page)
    ss_runtime.app.route('/readytoship')(ss_pages.ready_to_ship_page)
    ss_runtime.app.route('/ready_to_ship')(ss_pages.ready_to_ship_page)
    ss_runtime.app.route('/ready-to-ship')(ss_pages.ready_to_ship_page)
    ss_runtime.app.route('/api/ready-to-ship/prep-summaries', methods=['POST'])(ss_pages.ready_to_ship_prep_summaries)
    ss_runtime.app.route('/api/ready-to-ship/prep-context/<barcode>', methods=['GET'])(ss_pages.ready_to_ship_prep_context)
    ss_runtime.app.route('/alerts')(ss_pages.alerts_page)
    ss_runtime.app.route('/store-manager')(ss_pages.store_manager_page)
    ss_runtime.app.route('/mail-center')(ss_pages.mail_center_page)
    ss_runtime.app.route('/api/amazon-sns-webhook', methods=['POST'])(ss_mail_center.api_amazon_sns_webhook)
    ss_runtime.app.route('/api/mail-center/sync', methods=['POST', 'GET'])(ss_mail_center.api_mail_center_sync)
    ss_runtime.app.route('/api/mail-center/messages', methods=['GET'])(ss_mail_center.api_mail_center_messages)
    ss_runtime.app.route('/api/mail-center/messages', methods=['POST'])(ss_mail_center.api_mail_center_create_message)
    ss_runtime.app.route('/api/mail-center/send', methods=['POST'])(ss_mail_center.api_mail_center_send)
    ss_runtime.app.route('/api/mail-center/reply', methods=['POST'])(ss_mail_center.api_mail_center_reply)
    ss_runtime.app.route('/api/mail-center/messages/<int:message_id>/read', methods=['POST'])(ss_mail_center.api_mail_center_mark_read)
    ss_runtime.app.route('/label-master')(ss_pages.label_master_page)
    ss_runtime.app.route('/fb-listings')(ss_pages.fb_listings_page)
    ss_runtime.app.route('/store-listing-helper')(ss_pages.store_listing_helper_page)
    ss_runtime.app.route('/api/labelmaster/settings', methods=['GET'])(ss_shipping_labels.api_labelmaster_get_settings)
    ss_runtime.app.route('/api/labelmaster/settings', methods=['POST'])(ss_shipping_labels.api_labelmaster_save_settings)
    ss_runtime.app.route('/api/labelmaster/status', methods=['GET'])(ss_shipping_labels.api_labelmaster_status)
    ss_runtime.app.route('/api/labelmaster/orders', methods=['GET'])(ss_shipping_labels.api_labelmaster_orders)
    ss_runtime.app.route('/api/labelmaster/buy', methods=['POST'])(ss_shipping_labels.api_labelmaster_buy)
    ss_runtime.app.route('/api/labelmaster/print', methods=['POST'])(ss_shipping_labels.api_labelmaster_print)
    ss_runtime.app.route('/api/labelmaster/label', methods=['GET'])(ss_shipping_labels.api_labelmaster_label_file)
    ss_runtime.app.route('/api/pricemaster/listings', methods=['GET'])(ss_pricing.api_pricemaster_listings)
    ss_runtime.app.route('/api/pricemaster/bulk_update', methods=['POST'])(ss_pricing.api_pricemaster_bulk_update)
    ss_runtime.app.route('/api/pricemaster/ebay_verify', methods=['POST'])(ss_pricing.api_pricemaster_ebay_verify)
    ss_runtime.app.route('/api/pricemaster/feed_status', methods=['POST'])(ss_pricing.api_pricemaster_feed_status)
    ss_runtime.app.route('/api/listing-helper/scan', methods=['GET'])(ss_listing_alerts.api_listing_helper_scan)
    ss_runtime.app.route('/api/listing-helper/inventory-match', methods=['POST'])(ss_listing_alerts.api_listing_helper_inventory_match)
    ss_runtime.app.route('/api/listing-helper/dismiss', methods=['POST'])(ss_listing_alerts.api_listing_helper_dismiss)
    ss_runtime.app.route('/api/listing-helper/undismiss', methods=['POST'])(ss_listing_alerts.api_listing_helper_undismiss)
    ss_runtime.app.route('/api/listing-helper/dismissed', methods=['GET'])(ss_listing_alerts.api_listing_helper_dismissed)
    ss_runtime.app.route('/api/fb/listings', methods=['GET'])(ss_facebook.api_fb_listings)
    ss_runtime.app.route('/api/fb/listings/add', methods=['POST'])(ss_facebook.api_fb_listings_add)
    ss_runtime.app.route('/api/fb/listings/search_rawbol', methods=['GET'])(ss_facebook.api_fb_listings_search_rawbol)
    ss_runtime.app.route('/api/fb/listings/sync_sold', methods=['POST'])(ss_facebook.api_fb_listings_sync_sold)
    ss_runtime.app.route('/api/fb/listings/log', methods=['GET'])(ss_facebook.api_fb_listings_log)
    ss_runtime.app.route('/api/fb/listings/log/undo', methods=['POST'])(ss_facebook.api_fb_listings_log_undo)
    ss_runtime.app.route('/api/fb/listings/notes/<upc>', methods=['GET'])(ss_facebook.api_fb_listings_notes_get)
    ss_runtime.app.route('/api/fb/listings/notes', methods=['POST'])(ss_facebook.api_fb_listings_notes_add)
    ss_runtime.app.route('/api/fb/listings/notes/<int:note_id>', methods=['PUT'])(ss_facebook.api_fb_listings_notes_update)
    ss_runtime.app.route('/api/fb/listings/notes/<int:note_id>', methods=['DELETE'])(ss_facebook.api_fb_listings_notes_delete)
    ss_runtime.app.route('/api/fb/listings/quantity', methods=['POST'])(ss_facebook.api_fb_listings_quantity)
    ss_runtime.app.route('/api/fb/listings/unlist', methods=['POST'])(ss_facebook.api_fb_listings_unlist)
    ss_runtime.app.route('/trash-manager')(ss_inventory_archives.trash_manager_page)
    ss_runtime.app.route('/api/trash/settings', methods=['GET','POST'])(ss_inventory_archives.api_trash_settings)
    ss_runtime.app.route('/api/trash/list', methods=['GET'])(ss_inventory_archives.api_trash_list)
    ss_runtime.app.route('/api/trash/restore', methods=['POST'])(ss_inventory_archives.api_trash_restore)
    ss_runtime.app.route('/api/trash/hard_delete', methods=['POST'])(ss_inventory_archives.api_trash_hard_delete)
    ss_runtime.app.route('/api/trash/hard_delete_all', methods=['POST'])(ss_inventory_archives.api_trash_hard_delete_all)
    ss_runtime.app.route('/api/trash/purge_expired', methods=['POST'])(ss_inventory_archives.api_trash_purge_expired)
    ss_runtime.app.route('/api/debug/db_check', methods=['GET'])(ss_inventory_archives.api_debug_db_check)
    ss_runtime.app.route('/api/bol_items', methods=['GET'])(ss_bol_inventory.api_bol_items)
    ss_runtime.app.route('/api/bulk_delete_bol_items', methods=['POST'])(ss_bol_inventory.api_bulk_delete_bol_items)
    ss_runtime.app.route('/api/lots/select', methods=['POST'])(ss_bol_inventory.api_set_selected_lot)
    ss_runtime.app.route('/api/bol_lots', methods=['GET'])(ss_bol_inventory.api_bol_lots)
    ss_runtime.app.route('/api/lots', methods=['GET'])(ss_bol_inventory.api_bol_lots)
    ss_runtime.app.route('/api/bol_items/list_status', methods=['POST'])(ss_bol_inventory.api_bol_items_set_list_status)
    ss_runtime.app.route('/api/debug/migrate_listings', methods=['GET'])(ss_diagnostics.api_debug_migrate_listings)
    ss_runtime.app.route('/api/debug/check_item/<upc>', methods=['GET'])(ss_diagnostics.api_debug_check_item)
    ss_runtime.app.route('/api/cleanup_temporary_entry', methods=['POST'])(ss_diagnostics.api_cleanup_temporary_entry)
    ss_runtime.app.route('/api/items_prep/diagnostic/<upc>/photos.zip', methods=['GET'])(ss_prep_media.api_items_prep_diagnostic_photos_zip)
    ss_runtime.app.route("/token-status")(ss_ebay_auth.token_status)
    ss_runtime.app.route("/api/token-status")(ss_ebay_auth.api_token_status)
    ss_runtime.app.route("/", methods=["GET", "POST"])(ss_ebay_auth.home)
    ss_runtime.app.route("/callback")(ss_ebay_auth.callback)
    ss_runtime.app.route("/privacy")(ss_pages.privacy)
    ss_runtime.app.route("/search", methods=["POST"])(ss_pages.search)
    ss_runtime.app.route('/api/refresh_searchrack', methods=['POST'])(ss_enrichment.api_refresh_searchrack)
    ss_runtime.app.route('/api/enrich_status', methods=['GET'])(ss_enrichment.api_enrich_status)
    ss_runtime.app.route("/highlight")(ss_warehouse_maps.highlight)
    ss_runtime.app.route("/database")(ss_warehouse_maps.show_inventory)
    ss_runtime.app.route('/additemtrue', methods=['POST'])(ss_warehouse_receiving.additemtrue)
    ss_runtime.app.route("/barcode")(ss_warehouse_receiving.barcode_page)
    ss_runtime.app.route("/pictures")(ss_warehouse_receiving.pictures_page)
    ss_runtime.app.route("/position")(ss_warehouse_receiving.position_page)
    ss_runtime.app.route("/movelocation")(ss_warehouse_receiving.movelocation_page)
    ss_runtime.app.route("/fba-prep")(ss_warehouse_receiving.fba_prep_page)
    ss_runtime.app.route("/fba-labels")(ss_warehouse_receiving.fba_labels_page)
    ss_runtime.app.route('/position/diagnostic', methods=['POST'])(ss_warehouse_receiving.position_diagnostic)
    ss_runtime.app.route('/submitposition', methods=['POST'])(ss_warehouse_receiving.process_position)
    ss_runtime.app.route('/submitbarcode', methods=['POST'])(ss_warehouse_receiving.process_barcode)
    ss_runtime.app.route('/api/add-item/screen', methods=['POST'])(ss_warehouse_receiving.api_add_item_screen)
    ss_runtime.app.route('/additem', methods=['GET', 'POST'])(ss_warehouse_receiving.additem_page)
    ss_runtime.app.route('/additem-multi', methods=['GET'])(ss_warehouse_receiving.additem_multi_page)
    ss_runtime.app.route('/multibarcode', methods=['GET'])(ss_warehouse_receiving.multibarcode_page)
    ss_runtime.app.route('/toggle', methods=['POST'])(ss_warehouse_receiving.toggle)
    ss_runtime.app.route('/extractor/upload', methods=['POST'])(ss_raw_bol.extractor_upload)
    ss_runtime.app.route('/api/rawbol/upload', methods=['POST'])(ss_raw_bol.api_rawbol_upload)
    ss_runtime.app.route('/api/rawbol/backfill-retail', methods=['POST'])(ss_raw_bol.api_rawbol_backfill_retail)
    ss_runtime.app.route('/api/rawbol/view', methods=['GET'])(ss_raw_bol.api_rawbol_view)
    ss_runtime.app.route('/api/rawbol/logs', methods=['GET'])(ss_raw_bol.api_rawbol_logs)
    ss_runtime.app.route('/api/rawbol/stats', methods=['GET'])(ss_raw_bol.api_rawbol_stats)
    ss_runtime.app.route('/api/rawbol/delete/<lot_number>', methods=['DELETE'])(ss_raw_bol.api_rawbol_delete_lot)
    ss_runtime.app.route('/api/rawbol/update/<lot_number>', methods=['PUT'])(ss_raw_bol.api_rawbol_update_lot)
    ss_runtime.app.route('/api/rawbol/desync', methods=['POST'])(ss_raw_bol.api_rawbol_desync_all)
    ss_runtime.app.route('/api/sold/enrich-lot-numbers', methods=['POST'])(ss_raw_bol.api_sold_enrich_lot_numbers)
    ss_runtime.app.route('/api/sold/enrich-recent', methods=['POST'])(ss_raw_bol.api_sold_enrich_recent)
    ss_runtime.app.route('/api/rawbol/items/<lot_number>', methods=['GET'])(ss_raw_bol.api_rawbol_items)
    ss_runtime.app.route('/get-sold-orders', methods=['POST'])(ss_sales.get_sold_orders_route)
    ss_runtime.app.route('/api/amazon/test-connection', methods=['GET'])(ss_amazon_orders.test_amazon_connection)
    ss_runtime.app.route('/api/amazon/sync-orders', methods=['POST'])(ss_amazon_orders.sync_amazon_orders)
    ss_runtime.app.route('/api/amazon/sync-listings', methods=['POST'])(ss_amazon_orders.sync_amazon_listings)
    ss_runtime.app.route('/api/amazon/repair-titles', methods=['POST'])(ss_amazon_orders.repair_amazon_listing_titles)
    ss_runtime.app.route('/api/amazon/orders', methods=['GET'])(ss_amazon_orders.get_amazon_orders)
    ss_runtime.app.route('/sold-orders', methods=['GET'])(ss_sales.sold_orders)
    ss_runtime.app.route('/api/ready-to-ship/clear-location/<int:order_id>', methods=['POST'])(ss_shipping_orders.ready_to_ship_clear_location)
    ss_runtime.app.route('/api/ready-to-ship/count', methods=['GET'])(ss_shipping_orders.ready_to_ship_count)
    ss_runtime.app.route('/get-order', methods=['GET'])(ss_shipping_orders.get_order)
    ss_runtime.app.route('/api/ready-to-ship/note/<int:order_id>', methods=['POST'])(ss_shipping_orders.ready_to_ship_save_note)
    ss_runtime.app.route('/api/ready-to-ship/label/<int:order_id>', methods=['POST'])(ss_shipping_orders.ready_to_ship_upload_label)
    ss_runtime.app.route('/api/ready-to-ship/labels/upload', methods=['POST'])(ss_shipping_orders.ready_to_ship_upload_labels_bulk)
    ss_runtime.app.route('/api/ready-to-ship/labels/unmatched', methods=['GET'])(ss_shipping_orders.ready_to_ship_unmatched_labels)
    ss_runtime.app.route('/api/ready-to-ship/labels/all', methods=['DELETE'])(ss_shipping_orders.ready_to_ship_delete_all_labels)
    ss_runtime.app.route('/api/ready-to-ship/labels/unmatched/<int:label_id>', methods=['DELETE'])(ss_shipping_orders.ready_to_ship_delete_unmatched_label)
    ss_runtime.app.route('/api/ready-to-ship/labels/unmatched/<int:label_id>/file', methods=['GET'])(ss_shipping_orders.ready_to_ship_unmatched_label_file)
    ss_runtime.app.route('/api/ready-to-ship/labels/unmatched/<int:label_id>/print', methods=['POST'])(ss_shipping_orders.ready_to_ship_unmatched_label_print)
    ss_runtime.app.route('/api/ready-to-ship/label/<int:order_id>', methods=['DELETE'])(ss_shipping_orders.ready_to_ship_delete_label)
    ss_runtime.app.route('/api/ready-to-ship/label/<int:order_id>/<int:label_id>', methods=['DELETE'])(ss_shipping_orders.ready_to_ship_delete_order_label)
    ss_runtime.app.route('/api/ready-to-ship/label/<int:order_id>/file', methods=['GET'])(ss_shipping_orders.ready_to_ship_label_file)
    ss_runtime.app.route('/api/ready-to-ship/label/<int:order_id>/file/<int:label_id>', methods=['GET'])(ss_shipping_orders.ready_to_ship_order_label_file)
    ss_runtime.app.route('/api/ready-to-ship/label/<int:order_id>/print', methods=['POST'])(ss_shipping_orders.ready_to_ship_label_print)
    ss_runtime.app.route('/api/ready-to-ship/label/<int:order_id>/print/<int:label_id>', methods=['POST'])(ss_shipping_orders.ready_to_ship_order_label_print)
    ss_runtime.app.route('/api/ready-to-ship/location-options/<int:order_id>', methods=['GET'])(ss_shipping_orders.ready_to_ship_location_options)
    ss_runtime.app.route('/api/ready-to-ship/order-stats/<int:order_id>', methods=['GET'])(ss_shipping_orders.ready_to_ship_order_stats)
    ss_runtime.app.route('/mark-order-handled', methods=['POST'])(ss_sales_actions.mark_order_handled)
    ss_runtime.app.route('/mark-order-unhandled', methods=['POST'])(ss_sales_actions.mark_order_unhandled)
    ss_runtime.app.route('/api/sold/pending-removals', methods=['GET'])(ss_sales_repair.get_pending_removals)
    ss_runtime.app.route('/api/sold/cancel-removal/<int:order_id>', methods=['POST'])(ss_sales_repair.cancel_automatic_removal)
    ss_runtime.app.route('/api/sold/allow-removal/<int:order_id>', methods=['POST'])(ss_sales_repair.allow_automatic_removal)
    ss_runtime.app.route('/api/sold/trigger-automatic-removal', methods=['POST'])(ss_sales_repair.trigger_automatic_removal)
    ss_runtime.app.route('/api/sold/repair-missing-removals', methods=['POST'])(ss_sales_repair.repair_missing_removals)
    ss_runtime.app.route('/api/sold/removal-history/<int:order_id>', methods=['GET'])(ss_sales_repair.get_sold_removal_history)
    ss_runtime.app.route('/api/sold/find-inventory/<int:order_id>', methods=['GET'])(ss_sales_repair.find_inventory_for_sold)
    ss_runtime.app.route('/api/sold/match-barcode/<int:order_id>', methods=['POST'])(ss_sales_repair.match_barcode_to_sold)
    ss_runtime.app.route('/api/sold/debug-order/<int:order_id>', methods=['GET'])(ss_sales_repair.debug_sold_order)
    ss_runtime.app.route('/api/sold/debug-by-barcode/<barcode>', methods=['GET'])(ss_sales_repair.debug_sold_order_by_barcode)
    ss_runtime.app.route('/api/sold/reset-order/<int:order_id>', methods=['POST'])(ss_sales_repair.reset_sold_order)
    ss_runtime.app.route('/api/sold/manual-remove/<int:order_id>', methods=['POST'])(ss_sales_repair.manual_remove_sold_inventory)
    ss_runtime.app.route('/api/grace_period', methods=['GET'])(ss_inventory_cleanup.api_get_grace_period)
    ss_runtime.app.route('/api/grace_period', methods=['POST'])(ss_inventory_cleanup.api_set_grace_period)
    ss_runtime.app.route('/api/zero_qty_settings', methods=['GET'])(ss_inventory_cleanup.api_get_zero_qty_settings)
    ss_runtime.app.route('/api/zero_qty_settings', methods=['POST'])(ss_inventory_cleanup.api_set_zero_qty_settings)
    ss_runtime.app.route('/api/zero_qty_pending', methods=['GET'])(ss_inventory_cleanup.api_get_zero_qty_pending)
    ss_runtime.app.route('/api/zero_qty_delete_now/<barcode>', methods=['POST'])(ss_inventory_cleanup.api_zero_qty_delete_now)
    ss_runtime.app.route('/api/zero_qty_cancel/<barcode>', methods=['POST'])(ss_inventory_cleanup.api_zero_qty_cancel)
    ss_runtime.app.route('/api/zero_qty_allow/<barcode>', methods=['POST'])(ss_inventory_cleanup.api_zero_qty_allow)
    ss_runtime.app.route('/api/zero_qty/trigger-purge', methods=['POST'])(ss_inventory_cleanup.api_trigger_zero_qty_purge)
    ss_runtime.app.route('/api/inventory/history', methods=['GET'])(ss_inventory_history_views.api_inventory_history)
    ss_runtime.app.route('/api/removed', methods=['GET'])(ss_inventory_history_views.api_removed_list)
    ss_runtime.app.route('/removed')(ss_inventory_history_views.removed_page)
    ss_runtime.app.route('/api/removed/undo/<int:rem_id>', methods=['POST'])(ss_inventory_history_views.api_removed_undo)
    ss_runtime.app.route('/api/sold/remove-now/<int:order_id>', methods=['POST'])(ss_inventory_history_views.api_sold_remove_now)
    ss_runtime.app.route('/undo_match', methods=['POST'])(ss_inventory_history_views.undo_match)
    ss_runtime.app.route('/get_bol_upcs', methods=['GET'])(ss_bol_inventory.get_bol_upcs)
    ss_runtime.app.route('/upload_position_picture', methods=['POST'])(ss_warehouse_maps.upload_position_picture)
    ss_runtime.app.route("/pictureposition")(ss_warehouse_maps.pictureposition_page)
    ss_runtime.app.route('/set_pictureposition_path', methods=['POST'])(ss_warehouse_maps.set_pictureposition_path)
    ss_runtime.app.route('/searchrack')(ss_warehouse_maps.searchrack_page)
    ss_runtime.app.route('/api/inventory-quantity-history', methods=['GET'])(ss_analytics.api_inventory_quantity_history)
    ss_runtime.app.route('/api/sold-performance-history', methods=['GET'])(ss_analytics.api_sold_performance_history)
    ss_runtime.app.route('/finder')(ss_finder.finder_page)
    ss_runtime.app.route('/api/finder', methods=['POST'])(ss_finder.api_finder)
    ss_runtime.app.route('/api/finder/records', methods=['GET'])(ss_finder.api_finder_records)
    ss_runtime.app.route('/api/finder/aliases/forget', methods=['POST'])(ss_finder.api_finder_forget_alias)
    ss_runtime.app.route('/api/lookup-image-by-barcode', methods=['GET'])(ss_finder.api_lookup_image_by_barcode)
    ss_runtime.app.route('/api/finder/assign', methods=['POST'])(ss_finder.api_finder_assign)
    ss_runtime.app.route('/api/finder/remove', methods=['POST'])(ss_finder.api_finder_remove)
    ss_runtime.app.route('/api/finder/undo-remove', methods=['POST'])(ss_finder.api_finder_undo_remove)
    ss_runtime.app.route('/cleanup')(ss_inventory_cleanup.cleanup_page)
    ss_runtime.app.route('/unified-search')(ss_warehouse_search.unified_search_page)
    ss_runtime.app.route('/searchrack_api')(ss_warehouse_search.searchrack_api)
    ss_runtime.app.route('/searchbol_api')(ss_warehouse_search.searchbol_api)
    ss_runtime.app.route('/view_all/<db_type>')(ss_warehouse_search.view_all)
    ss_runtime.app.route('/update_item/<db_type>/<int:item_id>', methods=['POST'])(ss_warehouse_search.update_item)
    ss_runtime.app.route('/api/search/<db_key>', methods=['POST'])(ss_warehouse_search.api_search_db)
    ss_runtime.app.route('/api/search-all', methods=['POST'])(ss_warehouse_search.api_search_all)
    ss_runtime.app.route('/api/get_lot_numbers', methods=['GET'])(ss_warehouse_search.api_get_lot_numbers)
    ss_runtime.app.route('/api/bol_stats', methods=['GET'])(ss_warehouse_search.api_bol_stats)
    ss_runtime.app.route('/api/bol_stats/auto_assigned', methods=['GET'])(ss_warehouse_search.api_bol_stats_auto_assigned)
    ss_runtime.app.route('/api/lookup_location', methods=['POST'])(ss_warehouse_locations.api_lookup_location)
    ss_runtime.app.route('/api/set_rack_location', methods=['POST'])(ss_warehouse_locations.api_set_rack_location)
    ss_runtime.app.route('/api/update/<db_key>/<int:item_id>', methods=['POST'])(ss_warehouse_locations.api_update_row)
    ss_runtime.app.route('/api/check_shelf_code', methods=['POST'])(ss_shelves.api_check_shelf_code)
    ss_runtime.app.route('/api/create_shelf', methods=['POST'])(ss_shelves.api_create_shelf)
    ss_runtime.app.route('/api/update_shelf', methods=['POST'])(ss_shelves.api_update_shelf)
    ss_runtime.app.route('/api/clear_shelf_inventory/<code>', methods=['POST'])(ss_shelves.api_clear_shelf_inventory)
    ss_runtime.app.route('/api/list_shelves', methods=['GET'])(ss_shelves.api_list_shelves)
    ss_runtime.app.route('/api/shelf_counts', methods=['POST'])(ss_shelves.api_shelf_counts)
    ss_runtime.app.route('/api/groups', methods=['GET'])(ss_shelves.api_get_groups)
    ss_runtime.app.route('/api/create_group', methods=['POST'])(ss_shelves.api_create_group)
    ss_runtime.app.route('/api/delete_group', methods=['POST'])(ss_shelves.api_delete_group)
    ss_runtime.app.route('/api/move_shelves', methods=['POST'])(ss_shelves.api_move_shelves)
    ss_runtime.app.route('/api/upload_shelf', methods=['POST'])(ss_shelves.api_upload_shelf)
    ss_runtime.app.route('/api/delete_shelf', methods=['POST'])(ss_shelves.api_delete_shelf)
    ss_runtime.app.route('/api/valid_shelves', methods=['GET'])(ss_shelves.api_valid_shelves)
    ss_runtime.app.route('/api/location_hierarchy', methods=['GET'])(ss_shelves.api_location_hierarchy)
    ss_runtime.app.route('/api/fba-prep/barcode-guidance', methods=['GET'])(ss_fba_readiness.api_fba_prep_barcode_guidance)
    ss_runtime.app.route('/api/movelocation_lookup', methods=['GET'])(ss_warehouse_locations.api_movelocation_lookup)
    ss_runtime.app.route('/api/fba-prep/location-family', methods=['GET'])(ss_warehouse_locations.api_fba_prep_location_family)
    ss_runtime.app.route('/api/movelocation_lookup_shelf', methods=['GET'])(ss_warehouse_locations.api_movelocation_lookup_shelf)
    ss_runtime.app.route('/api/movelocation_execute', methods=['POST'])(ss_warehouse_locations.api_movelocation_execute)
    ss_runtime.app.route('/api/fba-prep/complete', methods=['POST'])(ss_warehouse_locations.api_movelocation_execute)
    ss_runtime.app.route('/api/fba-prep/amazon/readiness', methods=['GET', 'POST'])(ss_fba_shipments.api_fba_prep_amazon_readiness)
    ss_runtime.app.route('/api/fba-prep/amazon/plans', methods=['GET'])(ss_fba_shipments.api_fba_prep_amazon_plans)
    ss_runtime.app.route('/api/fba-prep/sessions/<int:session_id>/amazon/sync', methods=['GET'])(ss_fba_shipments.api_fba_prep_amazon_sync)
    ss_runtime.app.route('/api/fba-prep/sessions/<int:session_id>/amazon/<action>', methods=['POST'])(ss_fba_shipments.api_fba_prep_amazon_action)
    ss_runtime.app.route('/api/fba-prep/sessions/<int:session_id>/amazon/box-labels/<shipment_id>', methods=['GET'])(ss_fba_shipments.api_fba_prep_amazon_box_labels)
    ss_runtime.app.route('/api/fba-labels/resolve', methods=['GET'])(ss_fba_scanning.api_fba_labels_resolve)
    ss_runtime.app.route('/api/fba-prep/sessions/<int:session_id>/amazon/print-item-label', methods=['POST'])(ss_fba_scanning.api_fba_prep_amazon_print_item_label)
    ss_runtime.app.route('/api/fba-prep/sessions/<int:session_id>/amazon/pack-scan', methods=['POST'])(ss_fba_scanning.api_fba_prep_amazon_pack_scan)
    ss_runtime.app.route('/api/fba-prep/sessions/<int:session_id>/amazon/reset-pack-scan', methods=['POST'])(ss_fba_scanning.api_fba_prep_amazon_reset_pack_scan)
    ss_runtime.app.route('/api/fba-prep/sessions/<int:session_id>/count-scan', methods=['POST'])(ss_fba_scanning.api_fba_prep_count_scan)
    ss_runtime.app.route('/api/fba-prep/sessions/<int:session_id>/resolve-amazon-skus', methods=['POST'])(ss_fba_readiness.api_fba_prep_resolve_amazon_skus)
    ss_runtime.app.route('/api/fba-prep/sessions/<int:session_id>/validate-inbound', methods=['POST'])(ss_fba_readiness.api_fba_prep_validate_inbound)
    ss_runtime.app.route('/api/fba-prep/sessions/<int:session_id>/enable-fba', methods=['POST'])(ss_fba_readiness.api_fba_prep_enable_fba)
    ss_runtime.app.route('/api/fba-prep/sessions/<int:session_id>/resolve-fba-safety', methods=['POST'])(ss_fba_readiness.api_fba_prep_resolve_fba_safety)
    ss_runtime.app.route('/api/fba-prep/sessions/<int:session_id>/enable-fba-status', methods=['POST'])(ss_fba_readiness.api_fba_prep_enable_fba_status)
    ss_runtime.app.route('/api/fba-prep/sessions/<int:session_id>/live', methods=['GET', 'POST'])(ss_fba_sessions.api_fba_prep_session_live)
    ss_runtime.app.route('/api/fba-prep/sessions', methods=['GET', 'POST'])(ss_fba_sessions.api_fba_prep_sessions)
    ss_runtime.app.route('/api/fba-prep/sessions/<int:session_id>', methods=['GET', 'DELETE'])(ss_fba_sessions.api_fba_prep_session_detail)
    ss_runtime.app.route('/api/fba-prep/batches', methods=['GET'])(ss_fba_sessions.api_fba_prep_batches)
    ss_runtime.app.route('/api/fba-prep/batches/<int:batch_id>', methods=['GET'])(ss_fba_sessions.api_fba_prep_batch_detail)
    ss_runtime.app.route('/api/fba-prep/reviews', methods=['GET'])(ss_fba_sessions.api_fba_prep_reviews)
    ss_runtime.app.route('/api/fba-prep/reviews/<int:review_id>', methods=['POST'])(ss_fba_sessions.api_fba_prep_review_update)
    ss_runtime.app.route('/api/movelocation_bulk_cleanup', methods=['POST'])(ss_warehouse_locations.api_movelocation_bulk_cleanup)
    ss_runtime.app.route('/api/location_items', methods=['GET'])(ss_warehouse_locations.api_location_items)
    ss_runtime.app.route('/api/move_location', methods=['POST'])(ss_warehouse_locations.api_move_location)
    ss_runtime.app.route('/api/delete/<db_key>/<int:item_id>', methods=['POST'])(ss_inventory_archives.api_delete_row)
    ss_runtime.app.route('/api/undelete/<int:archive_id>', methods=['POST'])(ss_inventory_archives.api_undelete)
    ss_runtime.app.route('/api/location_duplicates', methods=['GET'])(ss_inventory_archives.api_location_duplicates)
    ss_runtime.app.route('/api/archived', methods=['GET', 'POST'])(ss_inventory_archives.api_archived_list)
    ss_runtime.app.route('/api/delete_archive/<int:archive_id>', methods=['POST'])(ss_inventory_archives.api_delete_archive)
    ss_runtime.app.route('/refresh_searchrack')(ss_pages.refresh_searchrack)
    ss_runtime.app.route('/test_sold_item', methods=['POST'])(ss_pages.test_sold_item)
    ss_runtime.app.route('/api/sync/status', methods=['GET'])(ss_sync.get_sync_status)
    ss_runtime.app.route('/api/sync/settings', methods=['POST'])(ss_sync.save_sync_settings)
    ss_runtime.app.route('/api/sync/all', methods=['POST'])(ss_sync.sync_all)
    ss_runtime.app.route('/api/sync/ebay-orders', methods=['POST'])(ss_sync.sync_ebay_orders_api)
    ss_runtime.app.route('/api/sync/ebay-listings', methods=['POST'])(ss_sync.sync_ebay_listings_api)
    ss_runtime.app.route('/api/sync/amazon-orders', methods=['POST'])(ss_sync.sync_amazon_orders_api)
    ss_runtime.app.route('/api/sync/amazon-listings', methods=['POST'])(ss_sync.sync_amazon_listings_api)
    ss_runtime.app.route('/api/sync/amazon-upcs', methods=['POST'])(ss_sync.sync_amazon_upcs_api)
    ss_runtime.app.route('/api/sync/recover-upcs', methods=['POST'])(ss_sync.recover_corrupted_upcs_api)
    ss_runtime.app.route('/api/sync/fix-amazon-barcodes', methods=['POST'])(ss_sync.fix_amazon_barcodes)
    ss_runtime.app.route('/api/sync/debug', methods=['GET'])(ss_sync.sync_debug)
    ss_runtime.app.route('/marketplace-sale')(ss_marketplace_sales.marketplace_sale)
    ss_runtime.app.route('/marketplace-session')(ss_marketplace_sales.marketplace_session)
    ss_runtime.app.route('/marketplace-stats')(ss_marketplace_sales.marketplace_stats)
    ss_runtime.app.route('/marketplace-schedule-pickup')(ss_marketplace_sales.marketplace_schedule_pickup)
    ss_runtime.app.route('/marketplace-live-pickups')(ss_marketplace_sales.marketplace_live_pickups)
    ss_runtime.app.route('/api/marketplace/generate-barcode', methods=['POST'])(ss_marketplace_sales.marketplace_generate_barcode)
    ss_runtime.app.route('/api/marketplace/lookup', methods=['GET'])(ss_marketplace_sales.api_marketplace_lookup)
    ss_runtime.app.route('/api/marketplace/search', methods=['GET'])(ss_marketplace_sales.api_marketplace_search)
    ss_runtime.app.route('/api/marketplace/pickups/search', methods=['GET'])(ss_marketplace_sales.api_marketplace_pickups_search)
    ss_runtime.app.route('/api/marketplace/pickups', methods=['GET'])(ss_marketplace_sales.api_marketplace_pickups)
    ss_runtime.app.route('/api/marketplace/pickups', methods=['POST'])(ss_marketplace_sales.api_marketplace_pickups_create)
    ss_runtime.app.route('/api/marketplace/sale', methods=['POST'])(ss_marketplace_sales.api_marketplace_sale)
    ss_runtime.app.route('/api/marketplace/decrement', methods=['POST'])(ss_marketplace_sales.api_marketplace_decrement)
    ss_runtime.app.route('/api/marketplace/sales', methods=['GET'])(ss_marketplace_sales.api_marketplace_sales)
    ss_runtime.app.route('/api/marketplace/sale/<int:sale_id>', methods=['DELETE'])(ss_marketplace_sales.api_marketplace_sale_delete)
    ss_runtime.app.route('/api/marketplace/sale/<int:sale_id>', methods=['PUT'])(ss_marketplace_sales.api_marketplace_sale_update)
    ss_runtime.app.route('/payouts')(ss_payouts.payouts_page)
    ss_runtime.app.route('/api/payouts', methods=['GET'])(ss_payouts.api_get_payouts)
    ss_runtime.app.route('/api/payouts/sync', methods=['POST'])(ss_payouts.api_sync_payouts)
    ss_runtime.app.route('/returns')(ss_returns.returns_page)
    ss_runtime.app.route('/api/returns', methods=['GET'])(ss_returns.api_get_returns)
    ss_runtime.app.route('/api/returns', methods=['POST'])(ss_returns.api_create_return)
    ss_runtime.app.route('/api/amazon/sync-returns', methods=['POST'])(ss_returns.api_sync_amazon_returns)
    ss_runtime.app.route('/api/ebay/sync-returns', methods=['POST'])(ss_returns.api_sync_ebay_returns)
    ss_runtime.app.route('/api/returns/<int:return_id>/mark-received', methods=['POST'])(ss_returns.api_mark_return_received)
    ss_runtime.app.route('/api/returns/<int:return_id>/restock', methods=['POST'])(ss_returns.api_restock_return)
    ss_runtime.app.route('/api/returns/<int:return_id>', methods=['PUT'])(ss_returns.api_update_return)
    ss_runtime.app.route('/api/returns/<int:return_id>', methods=['DELETE'])(ss_returns.api_delete_return)
    ss_runtime.app.route('/api/returns/<int:return_id>/relist', methods=['POST'])(ss_returns.api_relist_return)
    ss_runtime.app.route('/api/returns/<int:return_id>/resold', methods=['POST'])(ss_returns.api_resold_return)
    ss_runtime.app.route('/api/returns/<int:return_id>/restart-lifecycle', methods=['POST'])(ss_returns.api_restart_return_lifecycle)
    ss_runtime.app.route('/api/returns/<int:return_id>/history', methods=['GET'])(ss_returns.api_get_return_history)
    ss_runtime.app.route('/api/returns/<int:return_id>/undo-last-event', methods=['POST'])(ss_returns.api_undo_last_return_event)
    ss_runtime.app.route('/test-sold-orders')(ss_diagnostics.test_sold_orders_page)
    ss_runtime.app.route('/api/test-sold-order', methods=['POST'])(ss_diagnostics.api_create_test_sold_order)
    ss_runtime.app.route('/api/duplicate_shelf', methods=['POST'])(ss_shelves.api_duplicate_shelf)
    ss_runtime.app.route('/api/admin/cache/clear', methods=['POST'])(ss_cache_admin.api_admin_clear_cache)
    ss_runtime.app.route('/api/enrich-sold-db', methods=['POST'])(ss_cache_admin.api_enrich_sold_db)
    ss_runtime.app.route('/api/admin/cache/settings', methods=['GET', 'POST'])(ss_cache_admin.api_cache_settings)
