const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
(async () => {
 const browser = await chromium.launch({channel:'msedge', headless:true});
 for (const size of [{width:390,height:844},{width:820,height:1180}]) {
  const page = await browser.newPage({viewport:size,userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15'});
  const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  await page.setContent(`<meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font:17px system-ui;background:#f4f4f7;padding:20px}input,textarea{font:18px system-ui;padding:14px;width:85%}#modal{background:white;border-radius:16px;padding:20px}h2{font-size:22px}</style><div id="modal"><h2>Add item name</h2><label for="name">Warehouse name</label><input id="name" data-scanner-keyboard="on" autocapitalize="words" maxlength="200"><textarea id="note" data-scanner-keyboard="on"></textarea></div><input id="scan" data-scanner-keyboard="off">`);
  await page.addScriptTag({path:path.join(__dirname,'static/ios-scanner-keyboard.js')});
  await page.locator('#name').focus();
  const root=page.locator('#ss-ios-scanner-keyboard');
  await root.waitFor({state:'visible'});
  await page.waitForTimeout(500);
  const key=ch=>root.locator(`[data-ios-kb-char="${ch}"]:visible`);
  await key('h').click(); await key('i').click();
  assert.equal(await page.locator('#name').inputValue(),'Hi');
  await root.locator('[data-ios-kb-action="numbers"]:visible').click();
  await page.evaluate(()=>IOSScannerKeyboard.show(document.querySelector('#name')));
  await key('1').click();
  assert.equal(await page.locator('#name').inputValue(),'Hi1');
  await root.locator('[data-ios-kb-action="symbols"]:visible').click();
  await key('€').click();
  assert.equal(await page.locator('#name').inputValue(),'Hi1€');
  await root.locator('[data-ios-kb-action="letters"]:visible').click();
  await page.evaluate(()=>{const f=document.querySelector('#name');f.value='A👨‍👩‍👧‍👦';f.setSelectionRange(f.value.length,f.value.length)});
  await root.locator('[data-ios-kb-action="backspace"]:visible').click();
  assert.equal(await page.locator('#name').inputValue(),'A');
  await page.evaluate(()=>{const f=document.querySelector('#name');f.value='abcdefghij';f.setSelectionRange(10,10)});
  const del=await root.locator('[data-ios-kb-action="backspace"]:visible').boundingBox();
  await page.mouse.move(del.x+del.width/2,del.y+del.height/2);await page.mouse.down();await page.waitForTimeout(650);await page.mouse.up();
  const remaining=await page.locator('#name').inputValue();assert.ok(remaining.length<9);
  await page.waitForTimeout(180);assert.equal(await page.locator('#name').inputValue(),remaining);
  await page.evaluate(()=>{const f=document.querySelector('#name');f.value='';f.setSelectionRange(0,0)});
  const shift=root.locator('[data-ios-kb-action="shift"]:visible');
  await shift.click();await shift.click();await key('a').click();await key('b').click();
  assert.equal(await page.locator('#name').inputValue(),'AB');
  await shift.click();
  await page.evaluate(()=>{const f=document.querySelector('#name');f.value='hello';f.setSelectionRange(1,4)});
  await key('x').click();assert.equal(await page.locator('#name').inputValue(),'hxo');
  await page.evaluate(()=>{const f=document.querySelector('#name');f.maxLength=3;f.setSelectionRange(3,3)});
  await key('z').click();assert.equal(await page.locator('#name').inputValue(),'hxo');
  await page.evaluate(()=>{const f=document.querySelector('#name');f.maxLength=200;f.addEventListener('beforeinput',e=>e.preventDefault(),{once:true})});
  await key('z').click();assert.equal(await page.locator('#name').inputValue(),'hxo');
  await page.locator('#note').focus();await page.waitForTimeout(50);
  await key('a').click();await root.locator('[data-ios-kb-action="done"]:visible').click();
  assert.equal(await page.locator('#note').inputValue(),'A\n');
  assert.equal(await page.locator('#name').getAttribute('inputmode'),null);
  await page.locator('#name').focus();await page.waitForTimeout(80);
  await page.evaluate(()=>{document.querySelector('#name').value='Strawberry gummy bears'});
  await page.screenshot({path:path.join(__dirname,`keyboard-${size.width}.png`)});
  await page.evaluate(()=>document.querySelector('#modal').style.display='none');
  await page.waitForTimeout(300);assert.equal(await root.getAttribute('aria-hidden'),'true');
  assert.equal(await page.locator('#name').getAttribute('inputmode'),null);
  await page.locator('#scan').focus();await page.waitForTimeout(500);assert.equal(await root.getAttribute('aria-hidden'),'true');
  assert.deepEqual(errors,[]);
  await page.close();
 }
 await browser.close();console.log('Phone/tablet keyboard typing, layout, deletion, focus, dismissal and scanner exclusion passed');
})().catch(e=>{console.error(e);process.exit(1)});
